### ISSUE TITLE
Unclear error message from ClasspathFileSource.getZipEntryUri

### ISSUE THREAD

**Issue by tomasbjerre** [tomakehurst/wiremock#1039]
This code:
https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/common/ClasspathFileSource.java#L107

```
    private URI getZipEntryUri(final String name) {
        ZipEntry zipEntry = find(forEnumeration(zipFile.entries()), new Predicate<ZipEntry>() {
            public boolean apply(ZipEntry input) {
                return input.getName().equals(path + "/" + name);
            }
        });
        return getUriFor(zipEntry);
    }
```

May fail with something like:
```
java.util.NoSuchElementException
        at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:157)
        at com.google.common.collect.Iterators.find(Iterators.java:672)
        at com.github.tomakehurst.wiremock.common.ClasspathFileSource.getZipEntryUri(ClasspathFileSource.java:107)
        at com.github.tomakehurst.wiremock.common.ClasspathFileSource.getBinaryFileNamed(ClasspathFileSource.java:94)
        at com.github.tomakehurst.wiremock.http.StubResponseRenderer.renderDirectly(StubResponseRenderer.java:94)
        at com.github.tomakehurst.wiremock.http.StubResponseRenderer.buildResponse(StubResponseRenderer.java:65)
        at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:54)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
        at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:100)
```

And can be changed to fail with something more helpful. It would be helpful if the error included a list of all the entries that did not match.

**Comment by tomakehurst** [comment]
More than happy to merge a PR if you feel like creating one
