### ISSUE TITLE
Java 11 Compatibility

### ISSUE THREAD

**Issue by damonsutherland** [tomakehurst/wiremock#1072]
com.github.tomakehurst:wiremock:2.20.0
... com.jayway.jsonpath:json-path:2.4.0
...... net.minidev:json-smart:2.3
......... net.minidev:accessors-smart:1.2
............ org.ow2.asm:asm:5.0.4

We are unable to use WireMock 2.20.0 due to the use of a transitive dependency that is not compatible with Java 11.  The dependency tree in question is noted above.  Version 7.0.0 of asm is compatible with Java 11.  I am not sure if com.jayway.jsonpath has any updated versions.

If possible, could you track these issues down and address.  For now, unfortunately, I will need to use an alternative to wiremock. :(

**Comment by tomakehurst** [comment]
I just done a quick test with the asm dependency upgraded to 7.0 and it works fine, so I'll bump that up in the next release.

In the meantime, there should be nothing you stop you explicitly bumping the version up in your own dependencies.

**Comment by farmdawgnation** [comment]
+1 here - would like to use Wiremock but Java 11 is our standard environment.

**Comment by tomakehurst** [comment]
@farmdawgnation asm 7.0 already in there. What problem are you seeing when you attempt to run with Java 11?

**Comment by zak905** [comment]
I am seeing this 
```
java.lang.NoSuchMethodError: org.eclipse.jetty.util.thread.ReservedThreadExecutor.<init>(Ljava/util/concurrent/Executor;ILjava/lang/Object;)V

	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:263)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:278)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:238)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.server.Server.doStart(Server.java:397)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:182)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:146)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:69)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ber4444** [comment]
currently, 2.25.1 with jdk11 it is giving 
```
java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at wiremock.org.apache.http.conn.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:103)
	at com.github.tomakehurst.wiremock.http.HttpClientFactory.buildAllowAnythingSSLContext(HttpClientFactory.java:109)
```
similar to https://github.com/robolectric/robolectric/issues/5115

**Comment by alecharp** [comment]
Using `2.26.3`, I can see that `WireMockApp` is calling `Xml.optimizeFactoriesLoading()` method, which tries to load a class that is not exposed: `com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl`. 

It creates this stack-trace:

```
javax.xml.transform.TransformerFactoryConfigurationError: Provider com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl could not be instantiated: java.lang.reflect.InvocationTargetException
	at java.xml/javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:181)
	at java.xml/javax.xml.transform.FactoryFinder.find(FactoryFinder.java:257)
	at java.xml/javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:126)
	at com.github.tomakehurst.wiremock.common.Xml.optimizeFactoriesLoading(Xml.java:50)
	at com.github.tomakehurst.wiremock.core.WireMockApp.<clinit>(WireMockApp.java:77)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:72)
...
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:594)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.xml/javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:169)
	... 24 more
Caused by: java.lang.IllegalAccessError: class com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl (in unnamed module @0x441cc260) cannot access class jdk.xml.internal.JdkXmlUtils (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x441cc260
```

This is triggered as soon as we use the `WireMockServer`.

**Comment by tomakehurst** [comment]
@alecharp does this happen if you're not using Powermock?

**Comment by tomakehurst** [comment]
I'm going to close this, since `asm` got bumped to 7.0 a while back.

@alecharp if you're still experiencing the above issue, please could you post details on how to replicate in a new issue?
