### ISSUE TITLE
can not match xml as query parameter

### ISSUE THREAD

**Issue by deveilkwok** [tomakehurst/wiremock#1099]
- [] Which version of WireMock you're using
2.22.0
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
Java -jar wiremock-standalone-2.22.0.jar  --verbose

- [ ] A failing test case that demonstrates the problem

2. my configuration is as follows --------------------------
```
{
  "mappings": [
    {
      "request": {
        "method": "GET",
        "url": "/domesticTicketService.action"
      },
      "response": {
        "status": 200,
        "body": "Updated"

      }
    },
    {
      "id": "8c5db8b0-2db4-4ad7-a99f-38c9b00da3f7",
      "request": {
        "urlPathPattern": "/domesticTicketService.action(.*)",
        "queryParameters": {
          "requestXml": {
            "matchesXPath": "//operInfo:[operFuncno=\"DOMETICKET_FLIGHT_QUERY\"]"
          }
        }
      },
      "response": {
        "body": "OKKKK"
      }
    }
  ]
}
```

2. then I use curl or postman to send a request  -------------------------   
 what I want to match is that the operFuncno contains DOMETICKET_FLIGHT_QUERY

`curl 'http://localhost:8080/domesticTicketService.action?requestXml=<request><operInfo><operFuncname>aircheck</operFuncname><operFuncno>DOMETICKET_FLIGHT_QUERY</operFuncno><operatorType>1</operatorType><operator>yunfan2018@qq.com</operator><operatorPassword>22f5eb1121ba224c7b497719ba1b</operatorPassword></operInfo><flightQueryVo><enterpriseNo>enterpriseNo</enterpriseNo><fromCity>CAN</fromCity><destCity>PEK</destCity><departureDate>2019-03-25</departureDate><searchCityAirports>false</searchCityAirports></flightQueryVo></request>'
`
3. This does not workout as expected.  It seems the < or \ etc causing a problem in the matching. 
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /domesticTicketService.action. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.IllegalArgumentException: Illegal character in query at index 41: /domesticTicketService.action?requestXml=&lt;request&gt;&lt;operInfo&gt;&lt;operFuncname&gt;????&lt;/operFuncname&gt;&lt;operFuncno&gt;DOMETICKET_FLIGHT_QUERY&lt;/operFuncno&gt;&lt;operatorType&gt;1&lt;/operatorType&gt;&lt;operator&gt;yunfan2018@qq.com&lt;/operator&gt;&lt;operatorPassword&gt;22fa05eb1121b4ba224c7b497719ba1b&lt;/operatorPassword&gt;&lt;/operInfo&gt;&lt;flightQueryVo&gt;&lt;enterpriseNo&gt;enterpriseNo&lt;/enterpriseNo&gt;&lt;fromCity&gt;CAN&lt;/fromCity&gt;&lt;destCity&gt;PEK&lt;/destCity&gt;&lt;departureDate&gt;2019-03-25&lt;/departureDate&gt;&lt;searchCityAirports&gt;false&lt;/searchCityAirports&gt;&lt;/flightQueryVo&gt;&lt;/request&gt;
        at java.net.URI.create(URI.java:852)
        at com.github.tomakehurst.wiremock.matching.UrlPathPattern.match(UrlPathPattern.java:32)
        at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:81)
        at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:78)
        at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:176)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:183)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:181)
        at wiremock.com.google.common.collect.Iterators$6.computeNext(Iterators.java:617)
        at wiremock.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at wiremock.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at wiremock.com.google.common.collect.Iterators.getNext(Iterators.java:818)
        at wiremock.com.google.common.collect.Iterators.find(Iterators.java:688)
        at wiremock.com.google.common.collect.Iterables.find(Iterables.java:638)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:65)
        at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:172)
        at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:47)
        at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:529)
        at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
        at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in query at index 41: /domesticTicketService.action?
```

4. I have tried other like matches for the queryParameters， it does not work either . 

        "queryParameters": {
          "requestXml": {
            "matches": "^(.*)DOMETICKET_FLIGHT_QUERY"
          }

**Comment by tomakehurst** [comment]
Closing due to age and inactivity
