### ISSUE TITLE
CLI makes keystore required when truststore is specified

### ISSUE THREAD

**Issue by afilina** [tomakehurst/wiremock#1161]
## Which version of WireMock you're using
```
git: eb70b240169fcf1abbd86af36482d1c49826fa0b;
```

## How you're starting and configuring WireMock, including configuration or CLI the command line
```sh
java \
-cp /var/wiremock/lib/*:/var/wiremock/extensions/* \
com.github.tomakehurst.wiremock.standalone.WireMockServerRunner \
--root-dir=/stubs \
--port=80 \
--https-port=443 \
--https-truststore=/truststore.jks \
--truststore-password=password \
--https-require-client-cert \
--verbose \
--global-response-templating
```

## Expected behavior
Server starts with specified `https-truststore` while using the default `https-keystore`.

## Actual behavior
```
Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [https-keystore]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:140)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:52)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:125)
```

**Comment by multigrid101** [comment]
Same problem here

**Comment by srius** [comment]
Same with last version 2.27.2.
