### ISSUE TITLE
Problem with jsonBody and jsonPath in 2.24.x

### ISSUE THREAD

**Issue by andersflemmen** [tomakehurst/wiremock#1174]
As reported on the mailing list: https://groups.google.com/forum/#!topic/wiremock-user/AIrDDBbuZEA

We have been using a mapping like this with version 2.23.2:
```
{
  "request": {
    "method": "POST",
    "url" : "/test"
  },
  "response": {
    "status": 200,
    "jsonBody": {
      "modified": "{{jsonPath request.body '$.arrayprop.length()'}}"
    },
    "headers": {
      "Content-Type": "application/json"
    }
  }
}
```

such that the request 
`curl http://container:8080/test -X POST --data '{"arrayprop":["a","b"]}' `
returns 
`{"modified":"2"}`

We are starting WireMock with this command inside the docker container:
`java -cp /var/wiremock/lib/*:/var/wiremock/extensions/* com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --global-response-templating`

In 2.24.1 this does not work anymore, and WireMock gives a 500 response with a stack trace:
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /test. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>wiremock.com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at wiremock.com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at wiremock.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.getTemplate(ResponseTemplateTransformer.java:209)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:140)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:99)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:78)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:204)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:53)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:65)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:502)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.&lt;init&gt;(HandlebarsOptimizedTemplate.java:37)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer$2.call(ResponseTemplateTransformer.java:212)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer$2.call(ResponseTemplateTransformer.java:209)
	at wiremock.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at wiremock.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at wiremock.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at wiremock.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 36 more
</pre>
<h3>Caused by:</h3><pre>java.lang.NullPointerException
	at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.&lt;init&gt;(HandlebarsOptimizedTemplate.java:37)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer$2.call(ResponseTemplateTransformer.java:212)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer$2.call(ResponseTemplateTransformer.java:209)
	at wiremock.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at wiremock.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at wiremock.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at wiremock.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at wiremock.com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at wiremock.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.getTemplate(ResponseTemplateTransformer.java:209)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:140)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:99)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:78)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:204)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:53)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:65)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:502)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

**Comment by wasiek** [comment]
Hi @andersflemmen,
There is something wrong with resolving response body when one specifies `jsonBody`.
You could try to use below mapping for now. 

`{
    "request": {
        "method": "POST",
        "url": "/test"
    },
    "response": {
        "status": 200,
        "body": "{\"modified\":\"{{jsonPath request.body '$.arrayprop.length()'}}\"}",
        "headers": {
            "Content-Type": "application/json"
        }
    }
}`

I've check it with both versions 2.23.2 and 2.24.1 and it works as you expected returning `{"modified":"2"}` with your curl request. 

@tomakehurst 
When I've evaluated `matchingMapping.getResponse().body` I got the expected body as `Body {content={"modified":"{{jsonPath request.body '$.arrayprop.length()'}}"}, binary=false, json=true}`
but when i did the same with `matchingMapping.getResponse().getBody()` I got `null`.
branch:master; reference: com/github/tomakehurst/wiremock/stubbing/InMemoryStubMappings.java:79

This is because `getBody` now checkes if body `isJson`:
`    public String getBody() {
        return (!body.isBinary() && !body.isJson()) ? body.asString() : null;
    }
`
This was changed in #1117 

`null` is propagated to com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java:141 causing NPE

Please advise what to do.

**Comment by pmsgd** [comment]
Hello,
we have the same problem for:

```json
{
  "request": {
    "urlPathPattern": "/dataWarehouse/[\\w._]+/schema",
    "method": "POST"
  },
  "response": {
    "status": 302,
    "body": "{\"uri\": \"/dataWarehouse/{{request.requestLine.pathSegments.[3]}}/schema/default\"}",
    "headers": {
      "Location": "/dataWarehouse/{{request.requestLine.pathSegments.[3]}}/schema/default",
      "Content-Type": "application/json"
    },
    "transformers": [
      "response-template"
    ]
  }
}
```
