### ISSUE TITLE
Shutdown endpoint does not work with async responses enabled

### ISSUE THREAD

**Issue by stromnet** [tomakehurst/wiremock#1206]
In both Wiremock 2.25.0 and 2.25.1 (local build), when running Standalone wiremock with `--async-response-enabled true` then the `/__admin/shutdown` endpoint will not terminate the process properly.

My guess (as a newcomer to this codebase) is that the executor created at https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java#L369 is still left running, since threads are not (at least not explicitly) marked daemon.

### How to reproduce:

1. Launch wiremock
`java -jar java8/build/libs/wiremock-jre8-standalone-2.25.1.jar --port 10080 --print-all-network-traffic --async-response-enabled true`
2. Create a mapping with some delay:
  ```
cat > mapping.json << EOF
{
    "request": {
        "method": "GET",
        "url": "/some/thing"
    },
    "response": {
        "status": 200,
        "body": "Hello world!",
        "fixedDelayMilliseconds":500,
        "headers": {
            "Content-Type": "text/plain"
        }
    }
}
EOF
curl -X POST localhost:10080/__admin/mappings --data @mapping.json
```
3. Send at least one request to mapping, which is handled async: `curl localhost:10080/some/thing`
4. Send shutdown request: `curl -X POST localhost:10080/__admin/shutdown`

**Expected:** Wiremock process terminates.
**Actual:** wiremock process is alive, but HTTP server is no longer accepting connections.

process output at shutdown:
```
2019-10-15 09:08:35.050 Opened Socket[addr=/0:0:0:0:0:0:0:1,port=51854,localport=10080]
2019-10-15 09:08:35.051 Incoming bytes: POST /__admin/shutdown HTTP/1.1
Host: localhost:10080
User-Agent: curl/7.54.0
Accept: */*


2019-10-15 09:08:35.053 Outgoing bytes: HTTP/1.1 200 OK
Transfer-Encoding: chunked
Server: Jetty(9.4.20.v20190813)


2019-10-15 09:08:35.054 Outgoing bytes: 0


2019-10-15 09:08:35.054 Closed Socket[addr=/0:0:0:0:0:0:0:1,port=51854,localport=10080]
```

Sending -QUIT to the process reveals some threads still left:
```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode):

"pool-1-thread-1" #21 prio=5 os_prio=31 tid=0x00007fab3d129800 nid=0x5e03 waiting on condition [0x0000700010817000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007172f9ee8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"DestroyJavaVM" #19 prio=5 os_prio=31 tid=0x00007fab3d0fd000 nid=0x1803 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"qtp1693847660-17" #17 prio=5 os_prio=31 tid=0x00007fab3e8b0000 nid=0x5d03 waiting on condition [0x000070001050e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"qtp1693847660-16" #16 prio=5 os_prio=31 tid=0x00007fab3c817000 nid=0x5b03 waiting on condition [0x000070001040b000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"qtp1693847660-15" #15 prio=5 os_prio=31 tid=0x00007fab3c800000 nid=0xa603 waiting on condition [0x0000700010308000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"qtp1693847660-14" #14 prio=5 os_prio=31 tid=0x00007fab3b986800 nid=0x5903 waiting on condition [0x0000700010205000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"qtp1693847660-13" #13 prio=5 os_prio=31 tid=0x00007fab3e08b000 nid=0x5803 waiting on condition [0x0000700010102000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"qtp1693847660-12" #12 prio=5 os_prio=31 tid=0x00007fab3b163800 nid=0x5603 waiting on condition [0x000070000ffff000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"qtp1693847660-11" #11 prio=5 os_prio=31 tid=0x00007fab3a950800 nid=0x5503 waiting on condition [0x000070000fefc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000716ec9de0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:382)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.idleJobPoll(QueuedThreadPool.java:851)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:890)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fab3b812800 nid=0x3e03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fab3a81b800 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fab3a81b000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fab3a81a000 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fab3b033000 nid=0x3d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fab3b084800 nid=0x4a0b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fab3b04c000 nid=0x5103 in Object.wait() [0x000070000f6e4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000715588ed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x0000000715588ed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fab3b008000 nid=0x3503 in Object.wait() [0x000070000f5e1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000715586bf8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000715586bf8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x00007fab3a812800 nid=0x3403 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fab3d00a000 nid=0x1e07 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fab3b001800 nid=0x2103 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fab3b002000 nid=0x2a03 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fab3b002800 nid=0x5403 runnable

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007fab3b00b800 nid=0x2d03 runnable

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007fab3b00c800 nid=0x2f03 runnable

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007fab3d00a800 nid=0x3103 runnable

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007fab3d00b800 nid=0x3303 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007fab3b037000 nid=0x4003 waiting on condition

JNI global references: 415

Heap
 PSYoungGen      total 153088K, used 89480K [0x0000000715580000, 0x0000000720000000, 0x00000007c0000000)
  eden space 131584K, 68% used [0x0000000715580000,0x000000071ace2080,0x000000071d600000)
  from space 21504K, 0% used [0x000000071eb00000,0x000000071eb00000,0x0000000720000000)
  to   space 21504K, 0% used [0x000000071d600000,0x000000071d600000,0x000000071eb00000)
 ParOldGen       total 349696K, used 0K [0x00000005c0000000, 0x00000005d5580000, 0x0000000715580000)
  object space 349696K, 0% used [0x00000005c0000000,0x00000005c0000000,0x00000005d5580000)
 Metaspace       used 20036K, capacity 20368K, committed 20736K, reserved 1067008K
  class space    used 2412K, capacity 2534K, committed 2560K, reserved 1048576K
```

**Comment by tomakehurst** [comment]
Thanks for reporting this.

Would you consider creating a PR with a fix?

**Comment by stromnet** [comment]
If you give some hints on where it would be appropriate to tear it down, sure :)

**Comment by stromnet** [comment]
Daemon threads where enough, see PR.
