### ISSUE TITLE
Flaky NullPointer Exception within WireMockHandlerDispatchingServlet

### ISSUE THREAD

**Issue by rieckpil** [tomakehurst/wiremock#1224]
## Bug reports

Hi, we are using WireMock in a Spring Boot 2.2.1 Kotlin application for our integration tests. The WireMock Server is launched using a context initializer from Spring whenever the Spring Context launches:

```
@Order(Ordered.HIGHEST_PRECEDENCE)
class WireMockInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
  override fun initialize(applicationContext: ConfigurableApplicationContext) {
    val server = WireMockServer(wireMockConfig().dynamicPort()).apply {
      start()
    }

   // setting up our mocks and shutting down WireMock server when the Spring context closes
}

```

During our integration tests (using Maven Failsafe) we sometimes have failures once Spring launches a fresh context and Spring Security tries to get OAuth2 token (this call is stubbed within WireMock server):

```
[2019-11-20T18:46:11.102Z] 2019-11-20 18:46:10.860  WARN 1606 --- [p1428179993-219] org.eclipse.jetty.server.HttpChannel     : /oauth/endpoint
[2019-11-20T18:46:11.102Z] 
[2019-11-20T18:46:11.102Z] java.lang.NullPointerException: null
[2019-11-20T18:46:11.102Z] 	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
[2019-11-20T18:46:11.102Z] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1296)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1211)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.Server.handle(Server.java:500)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:386)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:562)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:378)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
[2019-11-20T18:46:11.102Z] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
[2019-11-20T18:46:11.102Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

This does not happen every time and is really flaky (maybe 2 out of 10 builds fail due to this issue).

We already enabled DEBUG logging for Jetty and used the ConsoleNotifier with verbose output from WireMock and couldn't get more insights.

The NPE happens at the following section within `WireMockHandlerDispatchingServlet`:
```
@Override
protected void service(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse) throws ServletException, IOException {
  LocalNotifier.set(notifier);

  Request request = new WireMockHttpServletRequestAdapter(httpServletRequest, multipartRequestConfigurer, mappedUnder);

  ServletHttpResponder responder = new ServletHttpResponder(httpServletRequest, httpServletResponse);
  requestHandler.handle(request, responder); // here the NPE happens
}
```

that means that something within the initialization of the `requestHandler` might not work all the time (`init` method of `WireMockHandlerDispatchingServlet`):

```
requestHandler = (RequestHandler) context.getAttribute(handlerClassName);
```

So do you maybe now any occurrences where this `ServletContext` does not contain the `StubRequestHandler`?

Any help is appreciated, we can't provide access to the code and know that it`s hard to reproduce.

**Comment by rieckpil** [comment]
We now have a workaround and add a simple e.g. `/readiness/wiremock` stub right after starting the `WireMockServer` and try to hit it with a simple retry-mechanism and once HTTP status 200 returns we continue we our setup.
