### ISSUE TITLE
Using "limit" as a query parameter in a request results in a 500 error.

### ISSUE THREAD

**Issue by drewtwo** [tomakehurst/wiremock#1241]
Running standalone process with wiremock-standalone-2.25.1.jar make any request(mocked or not) and include the query parameter "limit" in the request. The request works fine with other query parameters, but not with "limit".

sample json mapping
```
{
  "request": {
    "method": "GET",
    "urlPathPattern": "/test",
    "queryParameters": {
      "limit": {
        "matches": "^(.*)"
      }
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    },
    "jsonBody": {"some": "response"}
  }
}
```

Expected Result:
```
{
    "some": "response"
}
```

Actual Result:
```
java.lang.NullPointerException
	at java.lang.String.contains(String.java:2133)
	at com.github.tomakehurst.wiremock.matching.ContainsPattern.match(ContainsPattern.java:32)
	at com.github.tomakehurst.wiremock.matching.ContainsPattern.match(ContainsPattern.java:20)
	at com.github.tomakehurst.wiremock.matching.MultiValuePattern$1.apply(MultiValuePattern.java:79)
	at com.github.tomakehurst.wiremock.matching.MultiValuePattern$1.apply(MultiValuePattern.java:77)
	at wiremock.com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:638)
	at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at java.util.Collections.min(Collections.java:635)
	at com.github.tomakehurst.wiremock.matching.MultiValuePattern.getBestMatch(MultiValuePattern.java:83)
	at com.github.tomakehurst.wiremock.matching.MultiValuePattern.match(MultiValuePattern.java:55)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$4.apply(RequestPattern.java:250)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$4.apply(RequestPattern.java:248)
	at wiremock.com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at wiremock.com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
	at wiremock.com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699)
	at wiremock.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
	at wiremock.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
	at wiremock.com.google.common.collect.FluentIterable.toList(FluentIterable.java:614)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.allQueryParamsMatch(RequestPattern.java:246)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.access$300(RequestPattern.java:44)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:83)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:80)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:178)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:225)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:223)
	at wiremock.com.google.common.collect.Iterators$6.computeNext(Iterators.java:617)
	at wiremock.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at wiremock.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at wiremock.com.google.common.collect.Iterators.getNext(Iterators.java:818)
	at wiremock.com.google.common.collect.Iterators.find(Iterators.java:688)
	at wiremock.com.google.common.collect.Iterables.find(Iterables.java:638)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:71)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:204)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:53)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:65)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tomakehurst** [comment]
I'm struggling to replicate this one. I copied your stub example into my mappings and it worked fine with this curl command:

```
curl -v 'http://localhost:8888/test?limit=123'
```

Also, the fact that your pasted stack trace has the `ContainsPattern` class in it suggests that the stub given in the example isn't the one matching your request

Could you post your entire stub set and the HTTP request you're using?

**Comment by drewtwo** [comment]
Thank you for the response! I am re-looking at it based on your feedback and will update. I created a new sample project and it does indeed work(I thought for sure I had created a really simple project and it wasn't working which is what I pasted from). I deleted all my other mapping from my main project as well and was able get it working once I had only the trouble mapping left. This means it's likely something conflicting somehow between all my mappings in my client project. It's more likely than not an issue on my end and not a bug.

**Comment by drewtwo** [comment]
Okay, thank you again for responding. I have created a repo showing the possible issue:

https://github.com/drewtwo/wiremockExample

It is mostly on my side. If you look at [getBadLimitRequest.json](https://github.com/drewtwo/wiremockExample/blob/master/wiremock/mappings/getBadLimitRequest.json) it has limit included as a query parameter but the contains value is a number. In the [getSearchRequest.json](https://github.com/drewtwo/wiremockExample/blob/master/wiremock/mappings/getSearchRequest.json) the contains value is a string. The mock server spins up but the bad limit request breaks all other requests using the limit query parameter. 

In my project I have ~40 requests mocked out in separate files and only a couple use the limit parameter and I didn't think about checking if the other requests might have had an error. I apologize for not posting a better example initially.

**Comment by tomakehurst** [comment]
WireMock should probably do a better job of validating stub JSON in cases like this. It should reject a match operator with the wrong type on create (or startup if using files), rather than blowing up when a request is processed.

I'll mark this as a bug to be fixed, as I've just found out that (for some reason) the matcher gets coerced to an empty object when it can't be parsed, which is definitely dodgy.
