### ISSUE TITLE
Catch "java.net.SocketTimeoutException: Read timed out" when use a big JSON in stubFor()

### ISSUE THREAD

**Issue by akulik512** [tomakehurst/wiremock#1250]
Hi guys, 
I get the java.net.SocketTimeoutException when create stubFor() with big body (withBody(HUGE_JSON)).

Example:
```
public static void setUpRequest() throws Exception {
    stubFor(get(URL)
            .willReturn(aResponse().withHeader(CONTENT_TYPE, APPLICATION_JSON_VALUE)
                    .withStatus(OK.value())
                    .withBody(buildHugeJSON())));
}
```

```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at wiremock.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at wiremock.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at wiremock.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at wiremock.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at wiremock.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at wiremock.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at wiremock.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at wiremock.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at wiremock.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at wiremock.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at wiremock.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at wiremock.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at wiremock.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:436)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:417)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:133)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:292)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:287)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:106)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:110)
	...
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
```

But there is one moment.
When I removed whitespace and flattened JSON in one line test came to life! 
I stopped getting SocketTimeoutException!!
But after this, I added new value in this JSON and caught SocketTimeoutException again.

JBehave version: 4.1
Wiremock version: 2.23.2

**Comment by tomakehurst** [comment]
Does the same thing happen if you upgrade to the latest WireMock release (2.25.1)?

**Comment by kulik512** [comment]
> Does the same thing happen if you upgrade to the latest WireMock release (2.25.1)?

Sorry, I made a mistake.
I use this is:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-contract-wiremock</artifactId>
    <version>2.1.2.RELEASE</version>
    <scope>test</scope>
</dependency>
```
But, this is the same.
I tried to use the latest spring-cloud-contract-wiremock version and got the same result.
What can I try to do more to solve this problem or is it a bug?

**Comment by tomakehurst** [comment]
Using a body file instead of an inlined body would probably fix this.

**Comment by kulik512** [comment]
Are you talking about this? Do create myfile.xml file and call him in stubFor()?
```
stubFor(get(urlEqualTo("/body-file"))
        .willReturn(aResponse()
                .withBodyFile("path/to/myfile.xml")));

{
    "request": {
        "method": "GET",
        "url": "/body-file"
    },
    "response": {
        "status": 200,
        "bodyFileName": "path/to/myfile.xml"
    }
}
```

**Comment by tomakehurst** [comment]
Closing due to age and inactivity
