### ISSUE TITLE
loadMappingsFrom does not support bulk mappings files

### ISSUE THREAD

**Issue by pawoolley** [tomakehurst/wiremock#1267]
Hi,

I'm using `wiremock-jre8-2.26.0` and I'm trying to bulk load mappings from a local file.  The bulk mappings file json looks like this (with full request and response definitions omitted for brevity):
```javascript
{
    "mappings": [
        {
            "metadata": {
                "description": "Mapping #1"
            },
            "request": { ... },
            "response": { ... }
        },
        {
            "metadata": {
                "description": "Mapping #1"
            },
            "request": { ... },
            "response": { ... }
        }
    ]
}
```

...and I'm trying to load the mappings from a local directory like this:
```java
import com.github.tomakehurst.wiremock.client.WireMock;

// ...

WireMock wiremock = new WireMock(wiremockServerHost, wiremockServerPort);

/*
 * "/my/root/directory" contains a sub-directory called "mappings", which
 * contains the "mappings.json" file of bulk mappings.
 */
wiremock.loadMappingsFrom("/my/root/directory");
```

This results in the following exception as the `mappings` array is not expected/supported.
```
com.github.tomakehurst.wiremock.common.JsonException: {
  "errors" : [ {
    "code" : 10,
    "source" : {
      "pointer" : "/mappings"
    },
    "title" : "Error parsing JSON",
    "detail" : "Unrecognized field \"mappings\" (class com.github.tomakehurst.wiremock.stubbing.StubMapping), not marked as ignorable"
  } ]
}
	at com.github.tomakehurst.wiremock.common.JsonException.fromJackson(JsonException.java:53)
	at com.github.tomakehurst.wiremock.common.Json.read(Json.java:55)
	at com.github.tomakehurst.wiremock.stubbing.StubMapping.buildFrom(StubMapping.java:72)
	at com.github.tomakehurst.wiremock.standalone.RemoteMappingsLoader.load(RemoteMappingsLoader.java:49)
	at com.github.tomakehurst.wiremock.client.WireMock.loadMappingsFrom(WireMock.java:735)
    // ...remaining stacktrace omitted for brevity
```

I see that it is possible to bulk load mappings by POSTing the json to `/__admin/mappings/import`, but I was kinda expecting that `loadMappingsFrom` would support bulk mappings

Perhaps a `loadBulkMappingsFrom` method could be added, please?

For now, my workaround is to read in the bulk mappings json from file and register each stub mapping individually:
```java
import com.github.tomakehurst.wiremock.client.WireMock;
import com.github.tomakehurst.wiremock.stubbing.StubMappingCollection;
import com.github.tomakehurst.wiremock.common.Json;
import com.github.tomakehurst.wiremock.stubbing.StubMapping;

// ...

WireMock wiremock = new WireMock(wiremockServerHost, wiremockServerPort);

String bulkMappingsJsonString = loadContentsOfBulkMappingsFileToString();

StubMappingCollection stubMappingCollection = Json.read(
    updatedMappings,
    StubMappingCollection.class);

for (StubMapping stubMapping : stubMappingCollection.getMappings()) {
    wiremock.register(stubMapping);
}
```

**Comment by enoy19** [comment]
+1

**Comment by enoy19** [comment]
Same thing happens when using the @AutoConfigureWireMock spring annotation.
