### ISSUE TITLE
WireMock 2.26.1 and Handlebars NullPointerException

### ISSUE THREAD

**Issue by marcingrzejszczak** [tomakehurst/wiremock#1277]
## Bug reports

> We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [ ] Which version of WireMock you're using
Upgrading from 2.26 to 2.26.1

- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
Added on classpath in Spring Cloud Contract

When calling

```java
			Object value = WireMockHelpers.jsonPath.apply(context, options);
```

I see the following exception:

```

wiremock.com.github.jknack.handlebars.HandlebarsException: inline@217efa49:31:25: java.lang.NullPointerException
    inline@217efa49:31:25

	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.HandlebarsJsonPathHelper.getJsonDocument(HandlebarsJsonPathHelper.java:75)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.HandlebarsJsonPathHelper.apply(HandlebarsJsonPathHelper.java:48)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$3.apply(WireMockHelpers.java:50)
	at org.springframework.cloud.contract.verifier.builder.handlebars.HandlebarsJsonPathHelper.apply(HandlebarsJsonPathHelper.java:60)
	at wiremock.com.github.jknack.handlebars.internal.Variable.value(Variable.java:181)
	at wiremock.com.github.jknack.handlebars.internal.Variable.merge(Variable.java:160)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at wiremock.com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at wiremock.com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at wiremock.com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
	at org.springframework.cloud.contract.verifier.template.HandlebarsTemplateProcessor.uncheckedApplyTemplate(HandlebarsTemplateProcessor.groovy:102)
	
```

In the class I see the following code

```java
private DocumentContext getJsonDocument(Object json, Options options) {
        RenderCache renderCache = getRenderCache(options);
        RenderCache.Key cacheKey = RenderCache.Key.keyFor(DocumentContext.class, json);
        DocumentContext document = renderCache.get(cacheKey);
        if (document == null) {
            document = json instanceof String ?
                    JsonPath.parse((String) json) :
                    JsonPath.parse(json);
            renderCache.put(cacheKey, document);
        }

        return document;
    }
```

`renderCache` is null - which is a valid response option for `getRenderCache(...)`

```java
protected static RenderCache getRenderCache(Options options) {
        return (RenderCache)options.get("renderCache", (Object)null);
    }
```

Unfortunately then `renderCache.get` causes NPE.

**Comment by tomakehurst** [comment]
Ah, I see what you're doing here. I didn't really intend `RenderCache` (or the helpers generally) to ever be public, which is why I assumed it'd be safe to default it to null.

I'll change the default to a new instance to guarantee it's there if you call the helper directly.
