### ISSUE TITLE
Cannot request match when the request JSON body's element order is different from that specified in the Stub

### ISSUE THREAD

**Issue by damianperera** [tomakehurst/wiremock#1285]
- WireMock Version: `com.github.tomakehurst:wiremock-jre8:2.24.1`
- Framework: `Spring Boot 2.0.3 - Release`
- JUnit Version: `org.powermock:powermock-module-junit4:2.0.0-beta.5`
- WireMock Configuration:
```java
    @Rule
    public WireMockRule wireMockRule = new WireMockRule(options().bindAddress(WIREMOCK_HOST).port(WIREMOCK_PORT).notifier(new ConsoleNotifier(true)));
```
- Stub:
#### Stub
```java
stubFor(post(urlMatching(URL))
                    .withHeader("Content-Type", equalTo("application/json"))
                    .withRequestBody(equalToJson(REQUEST_BODY_JSON.toString(), true, true))
                    .willReturn(aResponse()
                            .withHeader("Content-Type", "application/json")
                            .withHeader("Connection", "close")
                            .withBody(RESPONSE_JSON.toString())));
```
### Issue Description
The following JSON object (which consists of a few key-value pairs and an array) is used in the `withRequestBody()` matcher.
```json
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3",
  "key4": "value4",
  "arr": [
    "arrValue1",
    "arrValue2",
    "arrValue3",
    "arrValue4"
  ]
}
```
When the following JSON is sent in the actual request body switching the order of the elements in the JSON object, WireMock fails to match it with the Stub.

```json
{
  "arr": [
    "arrValue1",
    "arrValue2",
    "arrValue3",
    "arrValue4"
  ],
  "key1": "value1",
  "key2": "value2",
  "key3": "value3",
  "key4": "value4"
}
```
### Actual Error
```
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
POST                                                       | POST
/mockStub                                                  | /mockStub
                                                           |
Content-Type: application/json                             | Content-Type: application/json
                                                           |
{                                                          | {                                                   <<<<< Body does not match
  "category" : "060",                                      |   "children" : [ {
  "date" : "20200312",                                     |     "id" : "9010946",
  "isRegistered" : true,                                   |     "age" : 1,
  "id" : "12302067",                                       |     "isRegistered" : false
  "children" : [ {                                         |   }, {
    "id" : "9405762",                                      |     "id" : "9405762",
    "age" : 1,                                             |     "age" : 1,
    "isRegistered" : true                                  |     "isRegistered" : true
  }, {                                                     |   }, {
    "id" : "9010946",                                      |     "id" : "9166586",
    "age": 1,                                              |     "age" : 1,
    "isRegistered" : false                                 |     "isRegistered" : false
  }, {                                                     |   }, {
    "id" : "7537984",                                      |     "id" : "7537984",
    "age" : 1,                                             |     "age" : 1,
    "isRegistered" : true                                  |     "isRegistered" : true
  }, {                                                     |   } ],
    "id" : "9166586",                                      |   "category" : "060",
    "age" : 1,                                             |   "id" : "12302067",
    "isRegistered" : false                                 |   "isRegistered" : true,
  } ]                                                      |   "date" : "20200312"
}                                                          | }
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

**Comment by damianperera** [comment]
This issue exists in WireMock `com.github.tomakehurst:wiremock-standalone:2.26.3` as well.

**Comment by aaron-goff** [comment]
Is it possible that the issue lies in your JSON being used to match? The output for the second item in your array looks malformed.

```
{
  "id" : "9010946",
  "age"isRegistered 1,
  "splitFlag": false
}
```

**Comment by tomakehurst** [comment]
Please try this with `wiremock-jre8:2.26.3`

**Comment by damianperera** [comment]
@aaron-goff my bad, that was a copy-paste error - I edited it with the correct snippet.

**Comment by damianperera** [comment]
@tomakehurst I'm getting the following error with this version when trying to init the Rule:
```
org/eclipse/jetty/util/ssl/SslContextFactory$Server
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ssl/SslContextFactory$Server
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.getServerConstructor(JettyHttpServerFactory.java:35)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory.<clinit>(JettyHttpServerFactory.java:30)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.<init>(WireMockConfiguration.java:79)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig(WireMockConfiguration.java:109)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.options(WireMockConfiguration.java:113)
```

**Comment by tomakehurst** [comment]
Suggest you try the standalone equivalent in that case: `wiremock-jre8-standalone:2.26.3`

**Comment by damianperera** [comment]
@tomakehurst it still happens in the standalone for `2.26.3`. Do you think there's something wrong with my implementation of the Stub or if this is a known behaviour in WireMock?

**Comment by damianperera** [comment]
@tomakehurst appears to be fixed in that version, any idea on the root cause of this?

**Comment by damianperera** [comment]
@tomakehurst it appears to be fixed in that version, any idea on the root cause of this?

**Comment by tomakehurst** [comment]
The JRE8 version of WireMock 2.26+ has a new underlying implementation for JSON equality that fixes some bugs regarding array order. The JRE7 version still uses the old impl because the library used by the new one is Java8+ only.

**Comment by damianperera** [comment]
@tomakehurst understood, thanks for the explanation! I'll close this issue now and will reopen it if the problem surfaces again :+1:
