### ISSUE TITLE
cannot use other port except 8080

### ISSUE THREAD

**Issue by bsc2xp** [tomakehurst/wiremock#1311]
Bug reports

 Using version 2.26.3 of Wiremock
 Using the stack builder library within Junit5 tests to execute stubbed endpoints
 Using gradle 6.2.1

here is code 

        WireMockServer wireMockServer = new WireMockServer(65000); //No-args constructor will start on port 8080, no HTTPS
        wireMockServer.start();
        stubFor(get(urlEqualTo("http://localhost:65000/test"))
                .willReturn(aResponse()
                        .withStatus(200)
                        .withHeader("Content-Type", "application/json")
                        .withBody(result.toJSONString())));

 Here is a summary of the error 

Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:473)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:454)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:131)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:298)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:293)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:104)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:108)

**Comment by tomakehurst** [comment]
You need to configure the static DSL to use your server's configured port:

```java
WireMock.configureFor(wireMockServer.port());
```
