### ISSUE TITLE
Wiremock crashes with UnknownHostException on linux if the hostname is not in /etc/hosts

### ISSUE THREAD

**Issue by jonenst** [tomakehurst/wiremock#1327]
## Bug reports

Wiremock crashes with UnknownHostException on linux if the hostname is not in /etc/hosts . Since the exception happens in a static initializer, this leads to ExceptionInInitializerError the first access and NoClassDefFoundError on the subsequent accesses. See this https://stackoverflow.com/questions/1881546/inetaddress-getlocalhost-throws-unknownhostexception 

Since they are Errors, most of the time they crash the whole test process.

Here's the stack trace.

Not sure what to do, either make this feature optional, or make it more robust accross OSs ?

Thanks,
Jon

```
Caused by: java.lang.ExceptionInInitializerError: null
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers$5.<init>(WireMockHelpers.java:62) ~[wiremock-jre8-standalone-2.26.2.jar:na]
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.WireMockHelpers.<clinit>(WireMockHelpers.java:61) ~[wiremock-jre8-standalone-2.26.2.jar:na]
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.<init>(ResponseTemplateTransformer.java:107) ~[wiremock-jre8-standalone-2.26.2.jar:na]
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.<init>(ResponseTemplateTransformer.java:83) ~[wiremock-jre8-standalone-2.26.2.jar:na]
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.<init>(ResponseTemplateTransformer.java:75) ~[wiremock-jre8-standalone-2.26.2.jar:na]
	at org.springframework.cloud.contract.wiremock.WireMockConfiguration.init(WireMockConfiguration.java:105) ~[spring-cloud-contract-wiremock-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 52 common frames omitted
Caused by: java.net.UnknownHostException: gm0winl149.bureau.si.interne: gm0winl149.bureau.si.interne: Erreur système
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642) ~[na:na]
	at com.github.tomakehurst.wiremock.extension.responsetemplating.helpers.HostnameHelper.<clinit>(HostnameHelper.java:31) ~[wiremock-jre8-standalone-2.26.2.jar:na]
	... 65 common frames omitted
Caused by: java.net.UnknownHostException: gm0winl149.bureau.si.interne: Erreur système
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[na:na]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[na:na]
	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1637) ~[na:na]
```

- [x] Which version of WireMock you're using
wiremock-jre8-standalone/2.26.2/
- [x] How you're starting and configuring WireMock, including configuration or CLI the command line
spring-cloud-starter-contract-stub-runner : mvn package
- [x] A failing test case that demonstrates the problem
see attached stacktrace, edit /etc/hosts to reproduce

**Comment by tomakehurst** [comment]
It's not great that it does an eager Inetaddress lookup on startup with the possibility of that failing. I'll look at putting some providing a safe fallback in the next version.

**Comment by jonenst** [comment]
Awesome thanks
