### ISSUE TITLE
[OutOfMemoryError] Multiple WireMockRule usage with many tests leads to OOM error

### ISSUE THREAD

**Issue by p3ch** [tomakehurst/wiremock#1346]
Hello,
faced problem with OutOfMemoryError running multiple wiremockServerRules

Found in
wiremock-jre8:2.26.3 with jetty 9.4.20.v20190813
still occures in 
wiremock-jre8:2.27.1 with jetty 9.4.30.v20200611

```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start(Thread.java:804)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThread(QueuedThreadPool.java:660)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.ensureThreads(QueuedThreadPool.java:642)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.doStart(QueuedThreadPool.java:182)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:190)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:147)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:69)
```

How i met this problem:
- using wiremock v2.26.3 with my springboot app
- upgraded spring from 2.1.8 to 2.2.0 - new jersey came 9.4.20.v20190813
- switched to wiremock-jre8 v2.26.3 which is based on 9.4.20.v20190813
- OutOfMemoryError

Bug is visible in this simple app https://github.com/p3ch/testing-with-wiremock
The problem is that on default wiremock conifguration with multiple wiremock rules jetty cannot cleanup hes threads :
```
"qtp1838704207-1871" #1871 prio=5 os_prio=31 cpu=0.17ms elapsed=13.75s tid=0x00007f955994f800 nid=0x15c703 waiting on condition  [0x000070007f7db000]
   java.lang.Thread.State: TIMED_WAITING (parking)
```
8K threads are created and test fails

Failing configuration is simple, like this 
https://github.com/p3ch/testing-with-wiremock/blob/master/src/test/groovy/simpleapp/crushing/CrushingBaseITSpec.groovy

Since main problem seems to be in not optimal method/class rule implementation (which starts and stops jetty server on every test method / class), quick fix is available too.

Solution is simple - changing default jettyStopTimeout to value > 0 (10ms, 1000ms, or default 30k - all seems to works fine) https://github.com/p3ch/testing-with-wiremock/blob/master/src/test/groovy/simpleapp/working/WorkingBaseITSpec.groovy#L49

Please consider switching default jettyStopTimeout from 0 to other value in 
https://github.com/tomakehurst/wiremock/blob/6ded3d6312cd19d9466343785fd58dc717c68e6a/src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java#L166

**Comment by tomakehurst** [comment]
Thanks for reporting this. I actually tripped over it myself a few months ago and I thought I'd already changed the default timeout, but clearly  I let that one slip.

I'll bump it up to 1s in the next release.
