### ISSUE TITLE
Spike in Memory Usage on Stopping Recording.

### ISSUE THREAD

**Issue by navaneeth-spotnana** [tomakehurst/wiremock#1353]
I am trying to record 5000 stubs at one go using Record feature. (More details [here](https://groups.google.com/g/wiremock-user/c/pJLOgMAz8YI)). When I stop recording, I see a huge spike in memory. I am able to reproduce the issue on standalone jar v2.27.0, so I thought of raising a issue here as well with steps to reproduce:

1) I am serving a medium/large JSON file (128kb) downloadable [here](https://gist.github.com/navaneeth-spotnana/43a831f21ab9e3223b56de888c1009cc) using a temporary HTTP server:

```
$ ls -lh
-rw-r--r--  1 xxxxx  staff    91B 27 Jul 14:09 caller.py
-rw-r--r--@ 1 xxxxx  staff   165K 27 Jul 15:52 response.json
$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

2) Created a python script `caller.py` that will call wiremock running in record mode, 5000 times:

```
import requests

for i in range(5000):
        requests.get('http://localhost:8080/response.json')
```

3) Run wiremock-standalone-2.27.0.jar, start recording, setting target url as `http://localhost:8000`, and then run `caller.py`

VisualVM Report:

![image](https://user-images.githubusercontent.com/57885431/88532864-f1a7e880-d022-11ea-8c45-770d933b9839.png)

In the heap graph, the slope around 4:02 PM is when I had sent the 5000 requests to the standalone jar.
Then after 4:03 PM, I pressed "Stop", and then I see a huge spike, after which the program ran out of heap space at 3500 MB.

Given the volume of request, the climb to 1000 MB (4:02 PM) is expected. But it then rising to few GBs at saving stubs is giving us trouble. What could be causing this? Can I somehow disable whatever is causing the spike and move on?

Stacktrace:
```
$ java -jar ~/Downloads/wiremock-standalone-2.27.0.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 /$$      /$$ /$$                     /$$      /$$                     /$$      
| $$  /$ | $$|__/                    | $$$    /$$$                    | $$      
| $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
| $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
| $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/ 
| $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$ 
| $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
|__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/

port:                         8080
enable-browser-proxying:      false
disable-banner:               false
no-request-journal:           false
verbose:                      false

2020-07-27 15:59:07.165 No response could be served as there are no stub mappings in this WireMock instance.
2020-07-27 15:59:07.165 No response could be served as there are no stub mappings in this WireMock instance.
2020-07-27 15:59:07.165 No response could be served as there are no stub mappings in this WireMock instance.
2020-07-27 15:59:07.165 No response could be served as there are no stub mappings in this WireMock instance.
2020-07-27 15:59:07.179 No response could be served as there are no stub mappings in this WireMock instance.
2020-07-27 15:59:13.221 No response could be served as there are no stub mappings in this WireMock instance.
2020-07-27 16:03:34.922 Unrecoverable error handling admin request
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
        at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:112)
        at wiremock.com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:430)
        at wiremock.com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
        at wiremock.com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1091)
        at com.github.tomakehurst.wiremock.common.Json.write(Json.java:83)
        at com.github.tomakehurst.wiremock.common.Json.write(Json.java:69)
        at com.github.tomakehurst.wiremock.recording.Recorder.stopRecording(Recorder.java:91)
        at com.github.tomakehurst.wiremock.core.WireMockApp.stopRecording(WireMockApp.java:466)
        at com.github.tomakehurst.wiremock.admin.StopRecordingTask.execute(StopRecordingTask.java:35)
        at com.github.tomakehurst.wiremock.http.AdminRequestHandler.handleRequest(AdminRequestHandler.java:86)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:64)
        at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:120)
        at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
        at wiremock.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:257)
        at wiremock.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:220)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
        at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
```

Thanks!

**Comment by tomakehurst** [comment]
The reason you see memory usage go up after pressing stop is that this is when the actual stub creation happens.

While the recorder is running, all WireMock is doing is logging requests and responses. Then you hit stop and it converts them all, at which point you've got both the request log and stubs in memory. It's slightly surprising to see it go to > 3x the memory needed for the log events, admittedly.

One thing I'd suggest in this instance is to record in batches by using the snapshot feature. To do this, you'd need to configure your own proxy stub (a broad match, low priority stub that proxies to your record target), then run the following loop as many times as needed:

* Clear the request log
* Make *n* requests, where *n* is your batch size
* Take a snapshot

By clearing the request log at the start of each batch you'd free the memory taken up by the previous batch.

BTW, I'd also suggest using `wiremock-jre8-standalone-2.27.1.jar` rather than the non-jre8 one.
