### ISSUE TITLE
Move away from Jetty or downgrade its version due to crashes on Android

### ISSUE THREAD

**Issue by ber4444** [tomakehurst/wiremock#1388]
```
W/System.err: Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
E/WireMockManager: Unable to start server
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:148)
```

this page - https://bugs.eclipse.org/bugs/show_bug.cgi?id=443652
suggests `last version of jetty 9.x that worked on android (api level 19) was 9.1.2.v20140210`

while your project uses `9.4.30.v20200611` of jetty

**Comment by ber4444** [comment]
```
Caused by: java.lang.RuntimeException: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:184)
at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:146)

Caused by: java.net.BindException: bind failed: EADDRINUSE (Address already in use)
at libcore.io.IoBridge.bind(IoBridge.java:99)
at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:132)
at java.net.ServerSocket.bind(ServerSocket.java:336)
at wiremock.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
at wiremock.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
at wiremock.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at wiremock.org.eclipse.jetty.server.Server.doStart(Server.java:366)
at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:182)
```

**Comment by ber4444** [comment]
#815 is another example of a jetty 9 crash on android

**Comment by tomakehurst** [comment]
Going to have a major rethink about Android support in 3.x. See https://github.com/tomakehurst/wiremock/issues/1345#issuecomment-829341603
