### ISSUE TITLE
can not work with jetty 9.4.35.v20201120

### ISSUE THREAD

**Issue by wujimin** [tomakehurst/wiremock#1412]
## Bug reports
- [x] Which version of WireMock you're using
        2.27.2  
        jetty version: 9.4.35.v20201120
        jetty is not the default 9.4.30.v20200611, because jetty old version have some vulnerability problem.
- [x] How you're starting and configuring WireMock, including configuration or CLI the command line
```java
        WireMockConfiguration config = WireMockConfiguration.wireMockConfig()
            .dynamicPort() // proxy port
            .dynamicHttpsPort()// mocker port
            .enableBrowserProxying(true);
        mockServer = new WireMockServer(config);
        mockServer.start();
```
- [x] A failing test case that demonstrates the problem
      * set log level to debug
      * register any stub
      * set web browser proxy to the proxy port
      * send request from web browser 
      will print ClassCastException  
```
java.lang.ClassCastException: class org.eclipse.jetty.io.ssl.SslConnection cannot be cast to class org.eclipse.jetty.server.HttpConnection (org.eclipse.jetty.io.ssl.SslConnection and org.eclipse.jetty.server.HttpConnection are in unnamed module of loader 'app')
	at org.eclipse.jetty.server.HttpInputOverHTTP.produceContent(HttpInputOverHTTP.java:33)
	at org.eclipse.jetty.server.HttpInput.consumeAll(HttpInput.java:721)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:412)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:820)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
```
  
when change jetty version from 9.4.35.v20201120 to 9.4.34.v20201102, there is no problem.

**Comment by wujimin** [comment]
when work with jetty version 9.4.36.v20210114, have the same problem too.

**Comment by DreierF** [comment]
Not very surprising, but it does also not work with Jetty 10 or 11.

**Comment by andreiastra** [comment]
Could you please prioritize this?

**Comment by tomakehurst** [comment]
Upgraded to latest Jetty 9.x in 64294f0a2a39c3eb308734d5bb73b6c6e16dc49a

**Comment by JeenaK** [comment]
Hi.. 
Wiremock 2.29.0 does not work with jetty 9.4.42.
Could you please update...

**Comment by wujimin** [comment]
try with jetty 9.4.40/41/42, all works.
but all of them have NPE problem:
```
java.lang.NullPointerException
	at org.eclipse.jetty.proxy.ProxyConnection.toConnectionString(ProxyConnection.java:86)
	at org.eclipse.jetty.io.AbstractEndPoint.toConnectionString(AbstractEndPoint.java:481)
	at org.eclipse.jetty.io.AbstractEndPoint.toString(AbstractEndPoint.java:450)
	at java.base@11.0.6/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
	at java.base@11.0.6/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
	at java.base@11.0.6/java.util.Formatter.format(Formatter.java:2673)
	at java.base@11.0.6/java.util.Formatter.format(Formatter.java:2609)
	at java.base@11.0.6/java.lang.String.format(String.java:2897)
	at org.eclipse.jetty.io.AbstractConnection.toString(AbstractConnection.java:296)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:624)
	at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:206)
	at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:95)
	at org.eclipse.jetty.io.AbstractConnection.onClose(AbstractConnection.java:225)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
```
