### ISSUE TITLE
Wiremock polutes system variables, which causes incompatibilities in multi-module-builds

### ISSUE THREAD

**Issue by henrykuijpers** [tomakehurst/wiremock#1420]
- [ 2.27.2 ] Which version of WireMock you're using
- [ Unit tests (JUnit) ] How you're starting and configuring WireMock, including configuration or CLI the command line
- [ ] A failing test case that demonstrates the problem

Issue is in: com.github.tomakehurst.wiremock.common.xml.Xml, where it sets System-wide JVM properties that define which TransformerFactory will be used.

WireMock should get rid of poluting system variables, by removing these statements, or at least make this configurable.
Otherwise, if they are intended to have a certain functionality in the command line tool, at least do not set them in the unit testing context.

Right now, this is failing our build in another module, with: 
```
Exception in thread "main" javax.xml.transform.TransformerFactoryConfigurationError: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
    at javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:181)
    at javax.xml.transform.FactoryFinder.find(FactoryFinder.java:216)
    at javax.xml.transform.TransformerFactory.newInstance(TransformerFactory.java:106)
    at sun.util.xml.PlatformXmlPropertiesProvider.emitDocument(PlatformXmlPropertiesProvider.java:174)
    at sun.util.xml.PlatformXmlPropertiesProvider.store(PlatformXmlPropertiesProvider.java:168)
    at java.util.Properties$XmlSupport.save(Properties.java:1208)
    at java.util.Properties.storeToXML(Properties.java:953)
    at java.util.Properties.storeToXML(Properties.java:908)
    at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.execute(GenerateMetadataMojo.java:497)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.ClassNotFoundException: org/apache/xalan/processor/TransformerFactoryImpl
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at javax.xml.transform.FactoryFinder.getProviderClass(FactoryFinder.java:127)
    at javax.xml.transform.FactoryFinder.newInstance(FactoryFinder.java:168)
    ... 31 more
```

**Comment by henrykuijpers** [comment]
This is an issue especially with `forkCount=0` set, which is used often to be able to debug Java-code while mvn is running unit tests.

**Comment by henrykuijpers** [comment]
This one is also not very prefered in a unit testing context: https://github.com/tomakehurst/wiremock/blob/788c0cff96b3cfb8d4d3b974c4090be9783a0f90/src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java#L46
We're not really using org.mortbay.logging.class property (or a framework that uses it), but the same polution/overwriting of other values is happening there.

**Comment by henrykuijpers** [comment]
@tomakehurst Any ideas / suggestions on this one? I would love to provide a PR to fix this issue, but I think it's good to have a discussion first on how to fix this (properly, or properly enough).

**Comment by tomakehurst** [comment]
It's not obvious how to fix this, but I agree having to set system vars isn't great.

I've not looked into this bit of Jetty's innards for a while, but there might be a way to set the logger programmatically per instance now. If you feel like investigating this, it would be a great start.

XML libraries are a real pain because they haven't evolved much since the days when everyone thought global system vars for everything was a great idea. I guess having a config parameter to override or disable this behaviour might be the least-worst option.

The call to `Xml.optimizeFactoriesLoading();` in `WireMockApp` could be moved from its current static block to the constructor so that it could be run conditionally based on a config flag.

**Comment by henrykuijpers** [comment]
For me, it would already be fine if that call in the static block in WireMockApp is surrounded with a system property-check (which defaults to true), so that we're able to override it with false.

Same for the Jetty property, I think.

**Comment by tomakehurst** [comment]
Hmmm...mixed feelings about having to set a system variable in order to suppress setting other system variables.

**Comment by henrykuijpers** [comment]
@tomakehurst  I agree on that. However, currently it is a pain to debug our unit tests when something is going wrong (as we have to set forkCount=0 to be able to attach our debugger properly - which is something we would prefer to leave on, instead of having to switch on/off all the time).

**Comment by henrykuijpers** [comment]
Have you been able to look into this a bit more, @tomakehurst ? Can I be of any assistance? :)

**Comment by henrykuijpers** [comment]
If there is a specific way we'd want to go tackling this, I'd be happy to provide at least a fix for the XML parser system properties. I think the logging would be tackled in #1471.

However, I don't know anything about the preferred way of developing WireMock.

**Comment by tomakehurst** [comment]
If you're happy to do so, how about creating a PR for the following:

* Create a config option to disable XML factory optimisation and move the call to `Xml.optimizeFactoriesLoading()` into the `WireMockApp` constructor so that it can be made conditional. We should also ensure it only gets called at most once here perhaps?
* Give similar treatment to `org.eclipse.jetty.server.HttpChannelState.DEFAULT_TIMEOUT` in `JettyHttpServer` but permit the actual timeout value to be set via config.

I *think* this line shouldn't matter, since it's only run in the context of the standalone process:

```java
System.setProperty("org.mortbay.log.class", "com.github.tomakehurst.wiremock.jetty.LoggerAdapter");
``` 

Or have you found a case where this is run when WireMock is used as a dependency?

**Comment by henrykuijpers** [comment]
@tomakehurst https://github.com/tomakehurst/wiremock/pull/1496

**Comment by henrykuijpers** [comment]
@tomakehurst What do you think about the changes?

**Comment by henrykuijpers** [comment]
@tomakehurst ping

**Comment by tomakehurst** [comment]
Please don't do that, I haven't forgotten.

In any case I added a review to the PR a week ago which you've not responded to yet.
