### ISSUE TITLE
Wiremock 2.29.0 does not work with jetty-9.4.42 as part of spring boot 2.5.1.

### ISSUE THREAD

**Issue by JeenaK** [tomakehurst/wiremock#1550]
# Issue guidelines

If you're asking a question, rather than reporting a bug or requesting a feature, **please post your question on the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user), and do not open an issue**.

Please do not log bugs regarding classpath issues (typically manifesting as 'NoClassDefFoundException' or 'ClassNotFoundException').
These are not WireMock bugs, and need to be diagnosed for your project using your build tool. Plenty has already been written in WireMock's issues and mailing list about how to resolve these issues
so please search these sources before asking for help.

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [ ] Which version of WireMock you're using
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
- [ ] A failing test case that demonstrates the problem
- [ ] Profiler data if the issue is performance related   

## Feature requests

Please include details of the use case and motivation for a feature when suggesting it.

**Comment by JeenaK** [comment]
Updated to latest spring boot 2.5.1 and came to find that wiremock-jre 2.29.0 is not picking the stubs properly with jetty-9.4.42.
Getting below error after upgrade:

java.lang.IllegalAccessError: class org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor tried to access private field org.eclipse.jetty.http.CompressedContentFormat._contentEncoding (org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor and org.eclipse.jetty.http.CompressedContentFormat are in unnamed module of loader 'app')

and hence it fails to load the http server

Caused by: org.apache.http.NoHttpResponseException: localhost:8081 failed to respond

**Comment by wujimin** [comment]
i try with jetty 9.4.40/41/42, all works.
but all of them have NPE problem:

```
java.lang.NullPointerException
	at org.eclipse.jetty.proxy.ProxyConnection.toConnectionString(ProxyConnection.java:86)
	at org.eclipse.jetty.io.AbstractEndPoint.toConnectionString(AbstractEndPoint.java:481)
	at org.eclipse.jetty.io.AbstractEndPoint.toString(AbstractEndPoint.java:450)
	at java.base@11.0.6/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
	at java.base@11.0.6/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
	at java.base@11.0.6/java.util.Formatter.format(Formatter.java:2673)
	at java.base@11.0.6/java.util.Formatter.format(Formatter.java:2609)
	at java.base@11.0.6/java.lang.String.format(String.java:2897)
	at org.eclipse.jetty.io.AbstractConnection.toString(AbstractConnection.java:296)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:624)
	at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:206)
	at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:95)
	at org.eclipse.jetty.io.AbstractConnection.onClose(AbstractConnection.java:225)
	at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:345)
	at org.eclipse.jetty.io.ManagedSelector$DestroyEndPoint.run(ManagedSelector.java:1104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
	at java.base@11.0.6/java.lang.Thread.run(Thread.java:834)
```
