### ISSUE TITLE
matchesXPath with equalToXml throws IllegalArgumentException: type: -1 randomly

### ISSUE THREAD

**Issue by RomainPruvostMHH** [tomakehurst/wiremock#1589]
Found after an upgrade of WireMock 2.27.1 to 2.30.1

We have the following mapping in our unit test which works well with Wiremock 2.27.1 : 
 ```
{
	"request": {
		"method": "POST",
		"url": "/my/path",
		"bodyPatterns": [
			{
				"matchesXPath": {
					"expression": "//identifiant",
					"equalToXml": "<identifiant>code_value_1</identifiant>"
				}
			}
		]
	},
	"response": {
		"status": 200,
		"headers": {
			"Content-Type": "text/xml"
		},
		"bodyFileName": "wiremock/data/mock.xml"
	}
}
 ```

After the upgrade to 2.30.1, the unit test which are unsing this mapping fails randomly (1 time in 4). When it failed, wiremock throws an exception : 
 ```
java.lang.IllegalArgumentException: type: -1
	at java.xml/com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl.getNodeObject(DeferredDocumentImpl.java:1063)
	at java.xml/com.sun.org.apache.xerces.internal.dom.DeferredDocumentImpl.synchronizeChildren(DeferredDocumentImpl.java:1723)
	at java.xml/com.sun.org.apache.xerces.internal.dom.DeferredElementImpl.synchronizeChildren(DeferredElementImpl.java:136)
	at java.xml/com.sun.org.apache.xerces.internal.dom.ParentNode.getFirstChild(ParentNode.java:227)
	at java.xml/com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.importNode(CoreDocumentImpl.java:1747)
	at java.xml/com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.cloneNode(CoreDocumentImpl.java:405)
	at java.xml/com.sun.org.apache.xerces.internal.dom.DocumentImpl.cloneNode(DocumentImpl.java:181)
	at org.xmlunit.util.Nodes.stripWhitespace(Nodes.java:93)
	at org.xmlunit.input.WhitespaceStrippedSource.<init>(WhitespaceStrippedSource.java:54)
	at org.xmlunit.builder.DiffBuilder.wrap(DiffBuilder.java:421)
	at org.xmlunit.builder.DiffBuilder.build(DiffBuilder.java:410)
	at com.github.tomakehurst.wiremock.matching.EqualToXmlPattern$1.isExactMatch(EqualToXmlPattern.java:134)
	at com.github.tomakehurst.wiremock.matching.WeightedMatchResult.isExactMatch(WeightedMatchResult.java:41)
	at com.github.tomakehurst.wiremock.matching.MatchResult$3.apply(MatchResult.java:100)
	at com.github.tomakehurst.wiremock.matching.MatchResult$3.apply(MatchResult.java:97)
	at com.google.common.collect.Iterators.all(Iterators.java:672)
	at com.google.common.collect.Iterables.all(Iterables.java:618)
	at com.github.tomakehurst.wiremock.matching.MatchResult$2.isExactMatch(MatchResult.java:70)
	at com.github.tomakehurst.wiremock.matching.WeightedMatchResult.isExactMatch(WeightedMatchResult.java:41)
	at com.github.tomakehurst.wiremock.matching.MatchResult$3.apply(MatchResult.java:100)
	at com.github.tomakehurst.wiremock.matching.MatchResult$3.apply(MatchResult.java:97)
	at com.google.common.collect.Iterators.all(Iterators.java:672)
	at com.google.common.collect.Iterables.all(Iterables.java:618)
	at com.github.tomakehurst.wiremock.matching.MatchResult$2.isExactMatch(MatchResult.java:70)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:227)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$3.apply(InMemoryStubMappings.java:225)
	at com.google.common.collect.Iterators.find(Iterators.java:714)
	at com.google.common.collect.Iterables.find(Iterables.java:646)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:73)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:209)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:57)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:64)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:127)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
 ```

**Comment by tomakehurst** [comment]
I can't replicate this from the info here.

Please can you share some more detail about your setup: How you're starting WM, Java version, the XML you're sending etc.?
