### ISSUE TITLE
Support for arbitrary HTTP methods

### ISSUE THREAD

**Issue by trejkaz** [tomakehurst/wiremock#228]
I'm working with WebDAV which uses a number of HTTP verbs that wiremock doesn't currently have in its enum:

    2015-01-29 14:31:48.592 /api/dav/
    java.lang.IllegalArgumentException: No enum constant com.github.tomakehurst.wiremock.http.RequestMethod.PROPFIND
    	at java.lang.Enum.valueOf(Enum.java:238)
    	at com.github.tomakehurst.wiremock.http.RequestMethod.valueOf(RequestMethod.java:23)
    	at com.github.tomakehurst.wiremock.jetty6.Jetty6HttpServletRequestAdapter.getMethod(Jetty6HttpServletRequestAdapter.java:76)
    	at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:49)
    	at com.github.tomakehurst.wiremock.verification.InMemoryRequestJournal.requestReceived(InMemoryRequestJournal.java:66)
    	at com.github.tomakehurst.wiremock.verification.InMemoryRequestJournal.requestReceived(InMemoryRequestJournal.java:72)
    	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:93)
    	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:35)
    	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:38)
    	at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.service(Jetty6HandlerDispatchingServlet.java:97)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

It would help if this structure were more flexible than an enum as any given new protocol could create new verbs and it's awkward to have to update the source each time.

**Comment by tomakehurst** [comment]
That's a fair shout I think. Fancy building a pull request?

**Comment by trejkaz** [comment]
Not sure. I think my quick fix will be to add to the enum which will get me around the hurdle while not really fixing the problem.

**Comment by jinahya** [comment]
Oh, I deadly want this feature added.

**Comment by Mahoney** [comment]
Should be working now on master - please confirm it's OK for you.

**Comment by handstandsam** [comment]
It looks like this issue is resolved and can be marked as resolved based on @Mahoney's accepted PR.

**Comment by tomakehurst** [comment]
I guess you're politely telling us we're overdue some issue gardening :-)

**Comment by handstandsam** [comment]
Just doing some tidying up for 2016 :-)
