### ISSUE TITLE
Null Pointer Exception for file in Very Large Data Set

### ISSUE THREAD

**Issue by timterrill** [tomakehurst/wiremock#234]
Hi,

My company is in the process of selecting a mocking solution that will need to support large datasets and high volume of requests for the purpose of integration and load testing.  I've run into two issues as I attempted to load and request 100,000 documents from wire mock.

I was using this version of java on a centOS 6.3 machine:

[~]$ java -version
java version "1.6.0_27"
Java(TM) SE Runtime Environment (build 1.6.0_27-b07)
Java HotSpot(TM) 64-Bit Server VM (build 20.2-b06, mixed mode)

1) I used the proxy record feature (worked nicely) and that part seemed to work just fine, except when I started wire mock up it crashed.  The issue was two empty JSON mapping files.  I'm not sure what happened there...I was using 3 threads to send requests thru the proxy so could that have been it?

I made them empty mapping files with  "{}" and it came up after 11 minutes (lots to initialize!).

2) Then I began to spot verify endpoints with curl:

[~]$ curl -D - "localhost:8081/loadtesting/dir-1/file-1"

The first one worked, then the second one:

[~]$ curl -D - "localhost:8081/loadtesting/dir-2/file-1"

gave me this:

2015-02-13 14:59:15.651 /loadtesting/dir-2/file-1                                                                                                                                                   [46/983]
java.lang.NullPointerException
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$1.apply(InMemoryStubMappings.java:87)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$1.apply(InMemoryStubMappings.java:85)
        at wiremock.com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
        at wiremock.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at wiremock.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at wiremock.com.google.common.collect.Iterators.getNext(Iterators.java:865)
        at wiremock.com.google.common.collect.Iterators.find(Iterators.java:733)
        at wiremock.com.google.common.collect.Iterables.find(Iterables.java:660)
        at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:39)
        at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:92)
        at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:35)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:38)
        at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.service(Jetty6HandlerDispatchingServlet.java:97)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at wiremock.org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at wiremock.org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at wiremock.org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at wiremock.org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at wiremock.org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at wiremock.org.mortbay.jetty.Server.handle(Server.java:326)
        at wiremock.org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at wiremock.org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at wiremock.org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at wiremock.org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at wiremock.org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at wiremock.org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at com.github.tomakehurst.wiremock.jetty6.DelayableSocketConnector$1.run(DelayableSocketConnector.java:49)
        at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

I located both body and mapping files and even loaded them into another instance of wire mock and it worked just fine there.  Here is the mapping file if it might help:

mappings/mapping-dir-2-file-1-jAQYT.json:
{
   "request" : {
      "url" : "/loadtesting/dir-2/file-1",
      "method" : "GET"
   },
   "response" : {
      "headers" : {
         "Server" : "Apache/2.2.25 (Fedora)",
         "X-Mockapp-Content-Path" : "/opt/data/mockdata/static/default/loadtesting/dir-2/file-1",
         "Age" : "0",
         "Accept-Ranges" : "bytes",
         "X-Mockapp-Rt-Time-Ms" : "227",
         "Connection" : "keep-alive",
         "X-Timer" : "0.251",
         "Content-Length" : "585",
         "X-Mockapp-Rt-Stats-Min" : "100",
         "X-Mockapp-Rt-Type" : "url",
         "X-Mockapp-Rt-Stats-Max" : "500",
         "Cache-Control" : "max-age=300",
         "Content-Type" : "application/json",
         "X-Varnish" : "371833293",
         "X-Mockapp-Header-Type" : "url",
         "Via" : "1.1 varnish",
         "Date" : "Thu, 12 Feb 2015 18:10:27 GMT"
      },
      "status" : 200,
      "fixedDelayMilliseconds" : "227",
      "bodyFileName" : "body-dir-2-file-1-jAQYT.json"
   }
}

I am in the process of testing it on my macbook pro running OS X 10.10.2 which uses this version of java, and it seems to be working better:

[~]$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Any assistance you could give would be great as I'm not a java developer, I'm a performance engineer looking to beat on this product, not debug it :)

Thanks,
Tim

**Comment by timterrill** [comment]
Ok, so I decided to write a follow up to this issue.  I think it had something to do with using Java 1.6.  When I upgraded to Java 1.7 i was able to access all 100k documents with no errors.  I did not look into the exact cause of the errors on 1.6, but I don't really care as I am not able to load test wire mock with 100k small documents!

**Comment by tomakehurst** [comment]
Thanks for posting your solution. I suspect we'll be dropping JDK6 support soon as it's way out of support  by Oracle now, and we'd like to upgrade to Jetty 9 which is JDK 7+.
