### ISSUE TITLE
Posting breaks for every second test method with Unexpected end of file from server exception

### ISSUE THREAD

**Issue by gpremer** [tomakehurst/wiremock#256]
For my project I noticed that a standalone unit test worked, but while executing the whole test suite, the test fails. I then experimented a bit and created this minimal test case:

``` java
import com.github.tomakehurst.wiremock.client.WireMock;
import com.github.tomakehurst.wiremock.junit.WireMockRule;

import org.junit.Rule;
import org.junit.Test;

import retrofit.RestAdapter;
import retrofit.http.Body;
import retrofit.http.POST;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.stubFor;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;

public class WireMockTest {

    @Rule
    public WireMockRule wireMockRule = new WireMockRule(19999);

    interface PostService {
        @POST("/post")
        String post(@Body Post post);
    }

    static class Post {
    }

    private static final RestAdapter restAdapter = new RestAdapter.Builder()
            .setEndpoint("http://localhost:19999")
            .setLogLevel(RestAdapter.LogLevel.FULL)
            .build();

    @Test
    public void testThatWireMockBreaks1() throws Exception {
        stubFor(
                WireMock.post(urlEqualTo("/post"))
                        .willReturn(aResponse()
                                .withStatus(200)
                                .withBody("ok")));

        restAdapter.create(PostService.class).post(new Post());
    }

    @Test
    public void testThatWireMockBreaks2() throws Exception {
        stubFor(
                WireMock.post(urlEqualTo("/post"))
                        .willReturn(aResponse()
                                .withStatus(200)
                                .withBody("ok")));

        restAdapter.create(PostService.class).post(new Post());
    }

    @Test
    public void testThatWireMockBreaks3() throws Exception {
        stubFor(
                WireMock.post(urlEqualTo("/post"))
                        .willReturn(aResponse()
                                .withStatus(200)
                                .withBody("ok")));

        restAdapter.create(PostService.class).post(new Post());
    }

    @Test
    public void testThatWireMockBreaks4() throws Exception {
        stubFor(
                WireMock.post(urlEqualTo("/post"))
                        .willReturn(aResponse()
                                .withStatus(200)
                                .withBody("ok")));

        restAdapter.create(PostService.class).post(new Post());
    }
}
```

As you can see there are 4 identical tests. The 1st and 3rd one pass, the 2nd and 4th ones fail with:

```
---> HTTP POST http://localhost:19999/post
Content-Type: application/json; charset=UTF-8
Content-Length: 2
{}
---> END HTTP (2-byte body)
---- ERROR http://localhost:19999/post
java.net.SocketException: Unexpected end of file from server
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
    at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at xxx.$Proxy15.post(Unknown Source)
    at xxx.WireMockTest.testThatWireMockBreaks4(WireMockTest.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:62)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

---- END ERROR

retrofit.RetrofitError: Unexpected end of file from server
    at retrofit.RetrofitError.networkError(RetrofitError.java:27)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at xxx.$Proxy15.post(Unknown Source)
    at xxx.WireMockTest.testThatWireMockBreaks4(WireMockTest.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:62)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.net.SocketException: Unexpected end of file from server
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
    at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
    ... 31 more
```

This is very similar to what was observed in issue 132. That issue was closed without a root cause being found however. I hope that providing a stand-alone, minimal test helps in tracking this down.

Other things I tried: 
- posting without a body : no breakage
- posting with a longer body : breaks
- connecting an actual server : no breakage => so not caused by retrofit
- switching from JDK 8 to JDK 7 : breaks => so likely not caused by JDK

My full dependency list:

```
testRuntime - Runtime classpath for source set 'test'.
+--- project :common
|    +--- io.reactivex:rxjava:1.0.8
|    +--- io.reactivex:rxandroid:0.24.0
|    |    \--- io.reactivex:rxjava:1.0.4 -> 1.0.8
|    \--- com.jakewharton:butterknife:6.1.0
+--- com.google.auto.value:auto-value:1.0
+--- com.squareup.retrofit:retrofit:1.9.0
|    \--- com.google.code.gson:gson:2.3.1
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
+--- org.easytesting:fest-assert-core:2.0M10
|    \--- org.easytesting:fest-util:1.2.5
+--- com.github.tomakehurst:wiremock:1.54
|    +--- org.apache.httpcomponents:httpclient:4.3.5
|    |    +--- org.apache.httpcomponents:httpcore:4.3.2
|    |    +--- commons-logging:commons-logging:1.1.3
|    |    \--- commons-codec:commons-codec:1.6
|    +--- org.slf4j:slf4j-api:1.7.6 -> 1.7.7
|    +--- xmlunit:xmlunit:1.5
|    +--- org.mortbay.jetty:jetty:6.1.26
|    |    +--- org.mortbay.jetty:jetty-util:6.1.26
|    |    \--- org.mortbay.jetty:servlet-api:2.5-20081211
|    +--- org.skyscreamer:jsonassert:1.2.3
|    |    \--- org.json:json:20090211
|    +--- com.jayway.jsonpath:json-path:0.8.1
|    |    +--- net.minidev:json-smart:1.1.1
|    |    \--- commons-lang:commons-lang:2.6
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.2
|    +--- com.fasterxml.jackson.core:jackson-core:2.4.2
|    +--- com.google.guava:guava:18.0
|    +--- net.sf.jopt-simple:jopt-simple:4.7
|    \--- com.fasterxml.jackson.core:jackson-databind:2.4.2
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.4.0 -> 2.4.2
|         \--- com.fasterxml.jackson.core:jackson-core:2.4.2
+--- org.apache.httpcomponents:httpcore:4.3.2
\--- ch.qos.logback:logback-classic:1.1.3
     +--- ch.qos.logback:logback-core:1.1.3
     \--- org.slf4j:slf4j-api:1.7.7
```

**Comment by gpremer** [comment]
One observation to add: the unexpected EOF also happens when a POST test is run between GET tests if it is run as an even invocation.

**Comment by oharsta** [comment]
I had the same problem and replaced the:
```
@Rule
public WireMockRule wireMockRule = new WireMockRule(19999);
```
with
```
@ClassRule
@Rule
public static WireMockClassRule wireMockRule = new WireMockClassRule(19999);
```
And that solved my problem. As you already indicated using 1.8 instead of 1.7 also solved my problem, but in this specific situation I was not able to go for 1.7 (yet)

**Comment by bernyfox** [comment]
Thanks @oharsta! I just experienced the same problem and your solution worked for me.
