### ISSUE TITLE
NullPointerException on request verification

### ISSUE THREAD

**Issue by pacey** [tomakehurst/wiremock#272]
I have a wire mock server running that receives several request with different combinations of query params. I would like to very that one of the requests was made with a certain query parameter set.

The verification process goes through all the requests and gets the query parameter you are looking for. However, if that request didn't have the parameter on it you get a null pointer. Should a null check be performed and then return false to say that request didn't match the verification?

Stack trace is as follows:
```
java.lang.NullPointerException
	at com.github.tomakehurst.wiremock.matching.RequestPattern$6.apply(RequestPattern.java:359)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$6.apply(RequestPattern.java:354)
	at com.google.common.collect.Iterators.all(Iterators.java:697)
	at com.google.common.collect.Iterables.all(Iterables.java:632)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.queryParametersMatch(RequestPattern.java:148)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.isMatchedBy(RequestPattern.java:95)
	at com.github.tomakehurst.wiremock.verification.InMemoryRequestJournal$1.apply(InMemoryRequestJournal.java:59)
	at com.github.tomakehurst.wiremock.verification.InMemoryRequestJournal$1.apply(InMemoryRequestJournal.java:57)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.size(Iterators.java:191)
	at com.google.common.collect.Iterables.size(Iterables.java:108)
	at com.github.tomakehurst.wiremock.verification.InMemoryRequestJournal.countRequestsMatching(InMemoryRequestJournal.java:48)
	at com.github.tomakehurst.wiremock.core.WireMockApp.countRequestsMatching(WireMockApp.java:158)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:252)
	at com.github.tomakehurst.wiremock.WireMockServer.verify(WireMockServer.java:253)
	at specs.SortSpec.should be able to change sort type(SortSpec.groovy:56) 
```

**Comment by tomakehurst** [comment]
I've recently merged a PR that fixes this. You shouldn't see this problem in 1.56.
