### ISSUE TITLE
Error when using com.fasterxml.jackson.core:jackson-core:2.5.3

### ISSUE THREAD

**Issue by Hypernation** [tomakehurst/wiremock#282]
When using the latest stable release of the jackson library WireMock throws an exception

java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonProperty.defaultValue()Ljava/lang/String;
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findPropertyDefaultValue(JacksonAnnotationIntrospector.java:468)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder$7.withMember(POJOPropertyBuilder.java:507)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder$7.withMember(POJOPropertyBuilder.java:504)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.fromMemberAnnotations(POJOPropertyBuilder.java:984)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder._findDefaultValue(POJOPropertyBuilder.java:504)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getMetadata(POJOPropertyBuilder.java:467)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._constructWriter(BeanSerializerFactory.java:714)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:567)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:351)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:270)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:223)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:152)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1166)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1120)
	at com.fasterxml.jackson.databind.SerializerProvider.findPrimaryPropertySerializer(SerializerProvider.java:624)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddPrimarySerializer(PropertySerializerMap.java:64)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:738)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:553)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:666)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1052)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:923)
	at com.github.tomakehurst.wiremock.common.Json.write(Json.java:40)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:65)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:138)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:134)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:65)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:69)
.......................

**Comment by Hypernation** [comment]
jackson version 2.6.0-rc1 gives the same stacktrace.

**Comment by tomakehurst** [comment]
Can you provide some setup details? Are you running standalone or inside an app or test case?

Which JVM version and vendor are you using?

**Comment by Hypernation** [comment]
Hi, 

We are using a standard oracle JDK 1.6.0_45, I also tried with a java 8 (jdk and runtime, but the exception is the same)

WireMock is booted in an Junit test using : 
   @Rule
    public WireMockRule wireMockRule = new WireMockRule(8098);
and the setup of the stub goes wrong :
stubFor(get(urlEqualTo("/mobile/147258369?p=test"))
                .willReturn(aResponse().withStatus(200).withBody(testJson))); 

In our maven setup we use : 

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.5.3</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.5.3</version>
		</dependency>

when switching them to 2.4.x  the test works.

example test :

import com.github.tomakehurst.wiremock.junit.WireMockRule;
import org.junit.Rule;
import org.junit.Test;

import static com.github.tomakehurst.wiremock.client.WireMock.*;


public class WireMockTest {

    @Rule
    public WireMockRule wireMockRule = new WireMockRule(8098);


    @Test
    public void setup() {

        stubFor(get(urlEqualTo("/mobile/147258369?p=data"))
                .willReturn(aResponse().withStatus(200).withBody("{data}")));
    }
}

**Comment by tomakehurst** [comment]
OK, so the problem is probably that you're supplying a version of Jackson that WireMock isn't compatible with.

I'd suggest switching your WireMock dependency to the standalone classifier as described here:
http://wiremock.org/getting-started.html

**Comment by Hypernation** [comment]
it was a dependency problem on my side!
after overriding the jackson-annotations dependency to the latest version to everything worked.

<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.5.3</version>
		</dependency>


thanks for the help !

**Comment by superevilchen** [comment]
Hello
Got this error msg as well.
Spring boot project with gradle.
build.gradle with versions:
```
"com.github.tomakehurst:wiremock-jre8:2.35.0"
"com.fasterxml.jackson.core:jackson-databind:2.14.1"
"com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.14.1"
```

Getting:
`Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findSubtypes(JacksonAnnotationIntrospector.java:627)

The following method did not exist:

    'boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()'

The calling method's class, com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector, was loaded from the following location:

    jar:file:<my-dir>/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.14.1/268524b9056cae1211b9f1f52560ef19347f4d17/jackson-databind-2.14.1.jar!/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.class

The called method's class, com.fasterxml.jackson.annotation.JsonSubTypes, is available from the following locations:

    jar:file:<my-dir>/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.13.4/858c6cc78e1f08a885b1613e1d817c829df70a6e/jackson-annotations-2.13.4.jar!/com/fasterxml/jackson/annotation/JsonSubTypes.class

The called method's class hierarchy was loaded from the following locations:

    com.fasterxml.jackson.annotation.JsonSubTypes: <mydir>/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.13.4/858c6cc78e1f08a885b1613e1d817c829df70a6e/jackson-annotations-2.13.4.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector and com.fasterxml.jackson.annotation.JsonSubTypes

`

The implementation (probably throws because it's a CLR that runs when context is loaded):
`@Component
@Profile("ct")
public class WiremockRecorder implements CommandLineRunner {

    @Override
    public void run(String... args) throws Exception {

        WireMockServer wireMockServer = new WireMockServer(options().port(8089));
        wireMockServer.start();
        wireMockServer.startRecording("http://localhost:8082");
    }
}`

Unfortunately I cannot change Jackson version (like suggested).
Is there another solution? perhaps another version of Wiremock? I didn't find any documentation regarding it except this issue ticket...
