### ISSUE TITLE
Intellij Issue When Running Cucumber Tests

### ISSUE THREAD

**Issue by cokleisli** [tomakehurst/wiremock#314]
Hi,

I seem to have an issue with WireMock running in Intellij. I have wiremock as an SBT dependency. If I run my cucumber tests from the command line, all is good. However, if I try to launch the cucumber tests from within Intellij, I get :

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Lorg/apache/http/conn/ssl/X509HostnameVerifier;)V
        at com.github.tomakehurst.wiremock.http.HttpClientFactory.createSslSocketFactory(HttpClientFactory.java:110)
        at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClientConnectionManagerWithSSLSettings(HttpClientFactory.java:88)
        at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:54)
        at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:70)
        at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.<init>(ProxyResponseRenderer.java:58)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:96)

Any idea why this is happening? I am using version 1.48, however I did try with the latest version but still the same error.

Regards,
Iftikhar

**Comment by tomakehurst** [comment]
This is probably because you have another version of the Apache HTTP client in your classpath. I suggest you use the standalone JAR, which shades this dependency out.
