### ISSUE TITLE
TrustManager issue

### ISSUE THREAD

**Issue by rbaldock** [tomakehurst/wiremock#327]
I'm having an issue running a JUnit test which includes a WireMockRule.

The endpoint is HTTP but I'm getting an error which seems to suggest WireMock wants to use HTTPS:

Caused by: java.security.NoSuchAlgorithmException: class configured for TrustManagerFactory: sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory not a TrustManagerFactory
	at sun.security.jca.GetInstance.checkSuperClass(GetInstance.java:258)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:237)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:138)
	at org.apache.http.conn.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:101)
	at com.github.tomakehurst.wiremock.http.HttpClientFactory.buildAllowAnythingSSLContext(HttpClientFactory.java:84)
	at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:63)
	at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.<init>(ProxyResponseRenderer.java:59)
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:103)

Googling suggests that adding @PowerMockIgnore("javax.net.ssl.*") at the top of the class should resolve this but this hasn't made any difference for me.

What could I be missing?

Robert

**Comment by tomakehurst** [comment]
Good chance another dependency in your project is messing with the Java TLS config. No idea what though if it's not Powermock. Suggest disabling other libraries one by one until the problem stops.

**Comment by rbaldock** [comment]
Thanks Tom.  I resolved this issue.  It was because I had the ignore annotation on a steps class rather than on the Cucumber test runner class.


Robert
