### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by aravinth610** [tomakehurst/wiremock#358]
I'm trying to proxy a web-application through reverse proxying.
I'm using wiremock-1.57 in standalone mode.
This is the command which I used,
java -jar wiremock-1.57-standalone.jar --port 8480 --https-port 8490 --https-keystore="/root/ssl.keystore" --keystore-password="keystore.password.to.be.replaced"  --proxy-all="https://10.152.13.120:443" --record-mappings --verbose 

When I tried this wiremock is logging out, 
EXCEPTION
javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1991)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1098)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:708)
        at com.github.tomakehurst.wiremock.jetty6.DelayableSslSocketConnector$1.run(DelayableSslSocketConnector.java:52)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

and in the client side I'm getting
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Untrusted certificate chain.

Can you please help me with this?

**Comment by tomakehurst** [comment]
Since this is a question, not a bug/feature request please can you re-post on the mailing list as per the README.
