### ISSUE TITLE
Running standalone wiremock with custom exten

### ISSUE THREAD

**Issue by KevinChiuKooppi** [tomakehurst/wiremock#364]
I am trying to run standalone wireMock with custom extension (downloaded as jar, https://github.com/opentable/wiremock-body-transformer).

CLI:
java -cp $jar path : wiremock-1.57-standalone.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions com.opentable.extension.BodyTransformer

 Then I get this exception:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:98)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:62)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:110)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Where is the problem relies in? Thanks a lot in advance.

**Comment by tomakehurst** [comment]
Please can you post questions to the mailing list. We prefer to keep issues for feature requests and bugs.
