### ISSUE TITLE
HTTPS/cert Proxy from standalone mode

### ISSUE THREAD

**Issue by pavelivanov-az** [tomakehurst/wiremock#409]
I'm running WireMock as a standalone service to provide mocks for some APIs and proxies for others in a complex system with many APIs/servers. It's working well for mocking, which is my first requirement, but proxying is giving me some trouble whether I use --proxy-all or stub mapping techniques.  

My reason for proxy is to be able to 1) capture the request/response as a baseline for building stubs since there may be many required, and 2) allow mocking of specific calls while using actual calls for others.

On a secondary note: I'd like to be able to use a host:port urlPattern instead of an API, but can't figure out how to capture that in request matching. I do see the 'Host' in the WireMock output and wonder how I can get at that information from request matching. 

A related enhancement might be to allow me to invoke an application from proxy mode rather than calling another server. That would allow me to have a hook on which to hang special handling as it arises.

Please see my problem statement followed by setup and run details below.

**Problem Statement**
I'm having some trouble getting WireMock to properly proxy (WireMock acting as a client) to a service on an HTTPS port requiring certs. In your docs you describe 'Proxying to a target server that requires client certificate authentication', which is what I believe I need, but I'm running in standalone mode so can't set up the WireMockRule as described.

I think my question is one of the following: 

- How do I define the WireMockRule (to use trustStore) from standalone mode?
- How can I run WireMock to pass the equivalent of '-k' when in proxy mode?
- How can I run WireMock in proxy mode to use cURL as the calling engine?

I get the desired response when running the request in cURL (which is what I intend WireMock proxy to run):
> curl -v -H 'Content-Encoding:xml' -H 'Content-Type:text/xml; encoding=UTF-8'  -X POST --data @/x/home/pivanov/service_request.xml -1 -k --cacert ./protected/generic_trusted_servers.pem --cert ./protected/generic_cert.pem --key ./protected/generic_key.pem --pass '<PEM pass phrase>'   https://<host>:10673/<api>

**Note**: If I run without '-k' I get an error:
curl: (51) SSL: certificate subject name 'generic_client' does not match target host name '<host>'

**Setup and Run Details**
I start WireMock using the following:

    java -jar wiremock-1.57-standalone.jar --port 7777 \
        --verbose --record-mappings \
        --jetty-header-buffer-size 16384 \
        --https-port 7778 \
        --https-keystore protected_package/protected.jks \
        --keystore-password passwordstg2 \
        --https-truststore protected_package/protected.jks \
        --truststore-password passwordstg2 \
        --match-headers="Accept,Content-Type,Content-Encoding" \
        --proxy-all "https://<host>:10673"

The mapping snippet that I hit (it overrides the --proxy-all above) follows. I'd like to be able to use a host:port urlPattern instead of an API, but can't figure out how to capture that in request matching.

        {
            "request": {
                "method": "POST",
                "urlPattern": "/<api>.*"
            },
            "response": {
                "proxyBaseUrl" : "https://<host>:10673"
            }
        }

**WireMock Error Output Snippet**

    2016-05-10 10:46:24.115 Request received:
    POST /myServer/1.0/myapi HTTP/1.1
    Host: <host>:7778^M
    Content-Type: application/x-www-form-urlencoded^M
    Encoding: XML^M
    Content-Length: 1800^M
    Correlation-Id: 7636f87d6e23c^M
    ............
    2016-05-10 10:46:24.124 Proxying: POST https://<host>:10673/<api>
    2016-05-10 10:46:24.312 /<api>
    java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException:  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
         at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:85)
        at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:47)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:40)
         at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.service(Jetty6HandlerDispatchingServlet.java:98)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at wiremock.org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at wiremock.org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at wiremock.org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at wiremock.org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at wiremock.org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at wiremock.org.mortbay.jetty.Server.handle(Server.java:326)
        at wiremock.org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at wiremock.org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
        at wiremock.org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at wiremock.org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at wiremock.org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at wiremock.org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at wiremock.org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:713)
        at com.github.tomakehurst.wiremock.jetty6.DelayableSslSocketConnector$1.run(DelayableSslSocketConnector.java:52)
        at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
    Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
        at wiremock.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at wiremock.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at wiremock.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at wiremock.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at wiremock.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at wiremock.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at wiremock.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at wiremock.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at wiremock.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:76)
        ... 19 more
    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:107)
        at wiremock.org.apache.http.conn.ssl.SSLContextBuilder$TrustManagerDelegate.checkServerTrusted(SSLContextBuilder.java:195)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:813)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323)
        ... 38 more
    Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 46 more

**Comment by pavelivanov-az** [comment]
This issue has been addressed in a newer version of Wiremock than I had installed.
