### ISSUE TITLE
How can I get a different KeyStore Type in Wiremock

### ISSUE THREAD

**Issue by abhagupta** [tomakehurst/wiremock#426]
Hi,
I am trying to make `https` run in  Wiremock mocking server with Android. Android supports 'BKS' keystore type instead of 'JKS' . 

Wiremock is using Jetty Server which should provide this keystore type internally . Wiremock is using the storetype  which is returned by default  `KeyStore.getDefaultType()`, which is good. [see here](https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/common/KeyStoreSettings.java#L47)
But there has to be a way by which Jetty Server used by Wiremock can be configured to use 'BKS' key store type.
In a standalone Jetty Server, this setting can be changed in a file like jetty-ssl-context.xml. with property
```
<Set name="KeyStoreType"><Property name="jetty.sslContext.keyStoreType" default="BKS"/></Set>
```
I have been walking through the source code of wiremock to see where this file is present or if its exposed for changes. Not been very successful so far.  If there is any clue on how to change this setting, it would help me save a lot of time.  Any other suggestion is also welcome.

For reference, here is error stack

```
Caused by: java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
at java.security.KeyStore.getInstance(KeyStore.java:119)
at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:52)
at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:871)
at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:273)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.server.Server.doStart(Server.java:366)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:101)
```

Thanks

**Comment by tomakehurst** [comment]
As per the README, please can you post questions on the mailing list, thanks.

**Comment by abhagupta** [comment]
Thanks @tomakehurst . I have created issue in mailing list.
