### ISSUE TITLE
NullPointerException when using JUnit rule with custom matcher

### ISSUE THREAD

**Issue by JFKnaufAncud** [tomakehurst/wiremock#458]
I am using Release 2.1.6

When implementing and invoking a custom matcher implementation (extends RequestMatcherExtension), a NullPointerException occurs in RequestPattern.match.

<pre><code>
java.lang.NullPointerException
	at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:125)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:116)
	at com.github.tomakehurst.wiremock.verification.NearMissCalculator$2.apply(NearMissCalculator.java:40)
	at com.github.tomakehurst.wiremock.verification.NearMissCalculator$2.apply(NearMissCalculator.java:38)
	at wiremock.com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at wiremock.com.google.common.collect.Iterators.addAll(Iterators.java:362)
	at wiremock.com.google.common.collect.Lists.newArrayList(Lists.java:160)
	at wiremock.com.google.common.collect.Iterables.toCollection(Iterables.java:337)
	at wiremock.com.google.common.collect.Iterables.toArray(Iterables.java:328)
	at wiremock.com.google.common.collect.Ordering.immutableSortedCopy(Ordering.java:842)
	at wiremock.com.google.common.collect.FluentIterable.toSortedList(FluentIterable.java:386)
	at com.github.tomakehurst.wiremock.verification.NearMissCalculator.sortAndTruncate(NearMissCalculator.java:57)
	at com.github.tomakehurst.wiremock.verification.NearMissCalculator.findNearestTo(NearMissCalculator.java:38)
	at com.github.tomakehurst.wiremock.core.WireMockApp.findNearMissesForUnmatchedRequests(WireMockApp.java:219)
	at com.github.tomakehurst.wiremock.client.WireMock.findNearMissesForAllUnmatchedRequests(WireMock.java:496)
	at com.github.tomakehurst.wiremock.WireMockServer.findNearMissesForAllUnmatchedRequests(WireMockServer.java:309)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.checkForUnmatchedRequests(WireMockRule.java:85)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.access$000(WireMockRule.java:33)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:73)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
</code></pre>

The Debugger says, it is customMatchers, that is null.

The corresponding rule in JUnit looks like

<pre><code>
		stubFor(requestMatching("MyCustomMatcher", MyCustomMatcherParameters).willReturn(
				aResponse().withStatus(200).withHeader("Content-Type", "application/json").withBody(expectedResponse)));
</code></pre>

**Comment by tomakehurst** [comment]
Thanks for pointing this out. I'll try and get a fix out tonight, as I think it's pretty trivial.

**Comment by tomakehurst** [comment]
I've pushed the fix in 2.1.7. Might take a few hours to get onto M2, but you can get it from oss.sonatype.org if you want to check it now.
