### ISSUE TITLE
com.github.tomakehurst.wiremock.verification.Diff.formatIfJsonOrXml bug

### ISSUE THREAD

**Issue by theangrydev** [tomakehurst/wiremock#477]
If you try to e.g. `verifyThat` with `equalToXml` and there is a non xml request, the method blows up:

```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at com.github.tomakehurst.wiremock.common.Xml.read(Xml.java:60)
	at com.github.tomakehurst.wiremock.common.Xml.prettyPrint(Xml.java:41)
	at com.github.tomakehurst.wiremock.verification.Diff.formatIfJsonOrXml(Diff.java:128)
	at com.github.tomakehurst.wiremock.verification.Diff.toString(Diff.java:112)
	at com.github.tomakehurst.wiremock.client.VerificationException.<init>(VerificationException.java:64)
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:39)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:353)

```

**Comment by tomakehurst** [comment]
Thanks. Replicated.

**Comment by theangrydev** [comment]
If you have the time, I'd appreciate this fix, it is blocking some tests I am writing :)

**Comment by theangrydev** [comment]
Thanks

**Comment by tomakehurst** [comment]
I've pushed a release. It usually takes a while to sync to M2, but you can grab it from oss.sonatype.org if you need it immediately.
