### ISSUE TITLE
Argument --help on standalone jar gives an exception

### ISSUE THREAD

**Issue by Wharenn** [tomakehurst/wiremock#483]
Hi,

I am using the standalone jar to use wiremock but I have this exception when using ``--help`` option:
```
java -jar wiremock-standalone-2.1.9.jar --help
```

The exception:

```
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key wiremock.joptsimple.BuiltinHelpFormatter.option.header
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at wiremock.joptsimple.internal.Messages.message(Messages.java:42)
        at wiremock.joptsimple.BuiltinHelpFormatter.message(BuiltinHelpFormatter.java:553)
        at wiremock.joptsimple.BuiltinHelpFormatter.addHeaders(BuiltinHelpFormatter.java:315)
        at wiremock.joptsimple.BuiltinHelpFormatter.addRows(BuiltinHelpFormatter.java:202)
        at wiremock.joptsimple.BuiltinHelpFormatter.format(BuiltinHelpFormatter.java:98)
        at wiremock.joptsimple.OptionParser.printHelpOn(OptionParser.java:327)
        at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.captureHelpTextIfRequested(CommandLineOptions.java:132)
        at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:115)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:52)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:113)
```

Is there any way to avoid this error? Until now, I was using version 1.55 which displayed it well.

Thank you

**Comment by tomakehurst** [comment]
Fixed by 75528a72f9c9fcc52a749e2bfad1b20627c8050f
