### ISSUE TITLE
NoSuchMethodError in 2.1.10+

### ISSUE THREAD

**Issue by oschwald** [tomakehurst/wiremock#499]
As of 2.1.10, [this code](https://github.com/maxmind/GeoIP2-java/blob/master/src/test/java/com/maxmind/geoip2/WebServiceClientTest.java#L347) is failing with the following exception:

```
java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.client.WireMock.get(Lcom/github/tomakehurst/wiremock/matching/UrlPattern;)Lcom/github/tomakehurst/wiremock/client/RemoteMappingBuilder;> is a java.lang.NoSuchMethodError
Stacktrace was: java.lang.NoSuchMethodError: com.github.tomakehurst.wiremock.client.WireMock.get(Lcom/github/tomakehurst/wiremock/matching/UrlPattern;)Lcom/github/tomakehurst/wiremock/client/RemoteMappingBuilder;
	at com.maxmind.geoip2.WebServiceClientTest.createClient(WebServiceClientTest.java:347)
	at com.maxmind.geoip2.WebServiceClientTest.createInsightsMeError(WebServiceClientTest.java:325)
	at com.maxmind.geoip2.WebServiceClientTest.test400WithUnexpectedContentType(WebServiceClientTest.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:72)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:421)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:386)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

2.1.9 works fine.

**Comment by tomakehurst** [comment]
Please can you post the code that is causing this exception

**Comment by oschwald** [comment]
I linked to it above, but here it is:

```
        stubFor(get(urlEqualTo("/geoip/v2.1/" + service + "/" + ip))
                .withHeader("Accept", equalTo("application/json"))
                .willReturn(aResponse()
                        .withStatus(status)
                        // This is wrong if we use non-ASCII characters, but we don't currently
                        .withHeader("Content-Length", Integer.toString(body.length))
                        .withHeader("Content-Type", contentType)
                        .withBody(body)));
```

**Comment by tomakehurst** [comment]
Apologies, reading on my phone and I missed that.

Can't see any obvious reason why you'd be seeing that, but it's probably worth pointing out that the ``RemoteMappingBuilder`` interface no longer exists (it was breaking Scala).

**Comment by oschwald** [comment]
I noticed that when going through the issues. I am not sure what is going on. I am certainly not using that directly anywhere.

**Comment by tomakehurst** [comment]
Are you somehow running some code that was compiled against the previous version?

Not sure what to suggest otherwise. I can take a proper look if you can post up a example project I can run.

**Comment by oschwald** [comment]
Indeed. With more testing, this appears to have been an issue with my CI Maven build configuration. Thanks for the help. I apologize for the invalid report.

**Comment by tomakehurst** [comment]
Glad you managed to get it sorted
