### ISSUE TITLE
Custom Request Matcher NPE when unmatched

### ISSUE THREAD

**Issue by marksievers** [tomakehurst/wiremock#517]
wiremock-standalone v2.2.1

When using a Custom `RequestMatcher` and an unmatched `Request` is encountered I am seeing the below Exception.
```
java.lang.NullPointerException
	at com.github.tomakehurst.wiremock.verification.Diff.toString(Diff.java:60)
	at com.github.tomakehurst.wiremock.client.VerificationException.<init>(VerificationException.java:64)
	at com.github.tomakehurst.wiremock.client.VerificationException.forSingleUnmatchedRequest(VerificationException.java:43)
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequests(VerificationException.java:48)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.checkForUnmatchedRequests(WireMockRule.java:87)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.access$000(WireMockRule.java:33)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:73)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
```

Looks like the [documentation](http://wiremock.org/docs/extending-wiremock/#custom-request-matchers) may be a bit out of date regarding custom matchers, so this could be an issue with the way I have set them up.

I've created a sample test that demonstrates the issue.
```java
import com.github.tomakehurst.wiremock.http.Request;
import com.github.tomakehurst.wiremock.junit.WireMockRule;
import com.github.tomakehurst.wiremock.matching.MatchResult;
import com.github.tomakehurst.wiremock.matching.RequestMatcher;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClientBuilder;
import org.junit.Rule;
import org.junit.Test;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.requestMatching;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig;

public class WmBugTest {

    @Rule
    public WireMockRule wireMockRule = new WireMockRule(wireMockConfig().dynamicPort());


    @Test
    public void wmBug() throws Exception {
        wireMockRule.stubFor(requestMatching(new CustomRequestMatcher())
                        .willReturn(aResponse()
                                    .withHeader("Content-Type", "text/plain")
                                    .withBody("Hi")));
        unmatchedGet();
    }

    private void unmatchedGet() throws Exception {
        HttpClient client = HttpClientBuilder.create().build();
        HttpGet request = new HttpGet("http://localhost:" + wireMockRule.port() + "/unmatched");
        request.addHeader("User-Agent", "foobar");
        HttpResponse response = client.execute(request);

        System.out.println("Response Code : " + response.getStatusLine().getStatusCode());
    }


    public static class CustomRequestMatcher extends RequestMatcher {
        @Override
        public String getExpected() {
            return "Some custom expectation";
        }

        @Override
        public MatchResult match(Request request) {
            if (request.getUrl().equals("foobar")) {
                return MatchResult.exactMatch();
            } else {
                return MatchResult.noMatch();
            }
        }

        @Override
        public String getName() {
            return "custom-request-matcher";
        }
    }
}

```

If this is not user-error, can anyone suggest a workaround just to have the `WireMockRule` not fail during (with this internal Exception) and instead fail with the unmatched call Exception?

I spent 45mins or so debugging through StubMapping, RequestPattern, NearMiss and Diff and didn't really come to any meaningful conclusion about what is at fault (eg should the Diff class be null safe or is the contract that urlMatcher should always be non-null). Happy to work on a pull request if someone can push me in the right direction.

**Comment by tomakehurst** [comment]
Thanks for raising this (and the full example in particular). I don't think there's a workaround unfortunately.

``Diff`` should definitely be null safe, since there's usually not a custom matcher present.

**Comment by marksievers** [comment]
@tomakehurst No problem.

Did you want a Pull Request? I have an interest in getting a solution into the next release :)

**Comment by tomakehurst** [comment]
Yes, a PR would be great. Thanks.

**Comment by tomakehurst** [comment]
Actually, don't worry. I'm about to push a fix.

**Comment by marksievers** [comment]
Fix looks good on the demo test, thanks for that.

`com.github.tomakehurst.wiremock.client.VerificationException: A request was unmatched by any stub mapping. Closest stub mapping was: (Request pattern had a custom matcher so no diff can be shown)
	at com.github.tomakehurst.wiremock.client.VerificationException.forSingleUnmatchedRequest(VerificationException.java:43)
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequests(VerificationException.java:48)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.checkForUnmatchedRequests(WireMockRule.java:87)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.access$000(WireMockRule.java:33)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:73)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)`
