### ISSUE TITLE
SSL errors when proxying with WireMock in Java 7 on Mac

### ISSUE THREAD

**Issue by yogurtearl** [tomakehurst/wiremock#55]
### Certain SSL certs will cause errors if you are trying to proxy thru WireMock on Java 7 on a Mac.

I am leaving this as a note to people encountering these exceptions.

The solution is to execute WireMock using Java 6 on your Mac. 
Depending on your setup you might find Java 6 here: /System/Library/Frameworks/JavaVM.framework/Home/bin/java

This may be more of a Java 7 issue than a WireMock issue, so you can close this if you like. Maybe you can add it to the documentation site. Also, maybe issue a warning at WireMock startup if it is running in Java 7. 

Here are some of the exceptions you might encounter:

```
java.lang.RuntimeException: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:75)
    at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:47)
    at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:40)
    at com.github.tomakehurst.wiremock.servlet.HandlerDispatchingServlet.service(HandlerDispatchingServlet.java:75)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at wiremock.org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at wiremock.org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
    at wiremock.org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
    at wiremock.org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at wiremock.org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at wiremock.org.mortbay.jetty.Server.handle(Server.java:326)
    at wiremock.org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at wiremock.org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
    at wiremock.org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at wiremock.org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at wiremock.org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at wiremock.org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at com.github.tomakehurst.wiremock.jetty.DelayableSocketConnector$1.run(DelayableSocketConnector.java:49)
    at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

```

```
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:541)
    at sun.security.ssl.InputRecord.read(InputRecord.java:374)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1328)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
    at wiremock.org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:708)
    at com.github.tomakehurst.wiremock.jetty.DelayableSslSocketConnector$1.run(DelayableSslSocketConnector.java:54)
    at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

```
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints
    at com.github.tomakehurst.wiremock.http.ProxyResponseRenderer.render(ProxyResponseRenderer.java:75)
    at com.github.tomakehurst.wiremock.http.StubResponseRenderer.render(StubResponseRenderer.java:47)
    at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:40)
    at com.github.tomakehurst.wiremock.servlet.HandlerDispatchingServlet.service(HandlerDispatchingServlet.java:75)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at wiremock.org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at wiremock.org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
    at wiremock.org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
    at wiremock.org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at wiremock.org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at wiremock.org.mortbay.jetty.Server.handle(Server.java:326)
    at wiremock.org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at wiremock.org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
    at wiremock.org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at wiremock.org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at wiremock.org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at wiremock.org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at wiremock.org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:713)
    at com.github.tomakehurst.wiremock.jetty.DelayableSslSocketConnector$1.run(DelayableSslSocketConnector.java:54)
    at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by handstandsam** [comment]
@yogurtearl Are you still having this issue?  Also, this may be fixed with the [2.0-beta branch] (https://github.com/tomakehurst/wiremock/tree/2.0-beta) now.

**Comment by tomakehurst** [comment]
Closing this due to its age. Please can anyone still seeing this issue open a fresh ticket with their setup details.

**Comment by calvarez-ov** [comment]
I'm currently having the`java.security.cert.CertificateException: Certificates does not conform to algorithm constraints` error running android unit tests with wiremock, but only on one PC, running tests on the command line. Works on other PCs on the command line, and works fine on this PC inside Android Studio.

When I find a solution, I'll add a new comment here to hopefully help anybody else who has this.

Unless somebody else finds the solution first and beats me to it :)
