### ISSUE TITLE
Verify failed since version 2.2.1

### ISSUE THREAD

**Issue by RaphC** [tomakehurst/wiremock#565]
Hi 

I'm facing an issue about the verify count. Since my upgrade to 2.4.1, the assertion fails saying the expected matches is not reached. I tested with 1.58,2.1.12 it's ok but from 2.2.X (I tested with 2.2.1,2.2.2,2.3.1,2.4.1,2.5.0) I get the following error : 

Expected exactly 4 requests matching the following pattern but received 3

My workaround was to set a 1s thread sleep between the end of my test and the verification.

What's changed since 2.2.X ? Is there any way to fix my problem without setting an ugly Thread.sleep?

Thanks,
Regards

**Comment by tomakehurst** [comment]
I'll need a bit more detail than this if I'm going to be able to figure out what the problem is.

Please can you post your code (or code that reliably reproduces this).

**Comment by RaphC** [comment]
Hi @tomakehurst 

Stack

- Spring framework 4.3.4.RELEASE
- Spring boot 1.4.2.RELEASE
- http component 4.5.2
- wiremock 2.5.0
- junit 4.12

Here is a unit test (BugWiremock) which reproduces the bug. My http client is declared as a bean in a Spring context :

/**
 * 
 */
package com.bouygtel.swad.gloud.aws.s3.service;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor;
import static com.github.tomakehurst.wiremock.client.WireMock.reset;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;
import static com.github.tomakehurst.wiremock.client.WireMock.verify;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig;

import java.io.IOException;

import org.apache.http.HttpStatus;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import com.github.tomakehurst.wiremock.common.Slf4jNotifier;
import com.github.tomakehurst.wiremock.core.WireMockConfiguration;
import com.github.tomakehurst.wiremock.junit.WireMockClassRule;


/**
 * @author RACHAUMI
 *
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {MySpringBootApplication.class})
public class BugWiremock {

	/**
	 * Configuration
	 */
	private static WireMockConfiguration wireMockConfig = wireMockConfig().dynamicPort().dynamicHttpsPort().notifier(new Slf4jNotifier(false));
	
	@Rule
	public WireMockClassRule awsMockRule = new WireMockClassRule(wireMockConfig);
	
	@Autowired
	private HttpClient httpClient;
	
	@Before
	public void before(){
		reset();
	}
	
	@After
	public void close(){
	}
	
	@Test
	public void get_with_request_timeout() {
		
		//given
		awsMockRule.stubFor(get(urlEqualTo("/my-url/2"))
	            .willReturn(aResponse()
		                .withFixedDelay(4000)
		                .withStatus(HttpStatus.SC_BAD_REQUEST)
		                .withHeader("x-amz-request-id", "D231426F7B")
		                .withHeader("x-amz-id-2", "LrifgSwZ163pt7")
		                .withHeader("ETag", "E338CFD231426F7BDEZADAD")
		                .withHeader("Date", "Wed, 12 Oct 2009 17:50:00 GMT")
		                .withHeader("Content-Length", "0")
		                .withHeader("Connection", "close")
		                .withHeader("Server", "AmazonS3")
	                ));
		
		
		//when
		for(int i=0;i<4;i++){
		try {
			httpClient.execute(new HttpGet(String.format("http://localhost:%s/my-url/2", awsMockRule.port())));
		} catch(IOException ioe){
			
		} finally {}
		}
		
		// On verifie qu'il y a bien eu 1 appel KO puis 3 tentatives derrieres
		verify(4, getRequestedFor(urlEqualTo("/my-url/2")));
	}
}

MySpringBootApplication.java

/**
 * 
 */
package com.bouygtel.swad.gloud.aws.s3.service;

import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.ServiceUnavailableRetryStrategy;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.protocol.HttpContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * @author RACHAUMI
 *
 */
@Configuration
public class MySpringBootApplication {

	
	@Bean
	public HttpClient httpClient(){
		return HttpClientBuilder.create()
				.setServiceUnavailableRetryStrategy(new ServiceUnavailableRetryStrategy() {

		            @Override
		            public long getRetryInterval() {
		                return 0;
		            }

					@Override
					public boolean retryRequest(HttpResponse response, int executionCount, HttpContext context) {
						
						int statusCode = response.getStatusLine().getStatusCode();
						return statusCode != 200 && executionCount < 4;
					}
		        })
				.setDefaultRequestConfig(RequestConfig.custom().setSocketTimeout(1000).setConnectTimeout(1000).setConnectionRequestTimeout(1000).build())
											.build();
	}
}



My log output

2017-01-09 15:21:39.384 INFO [main] BugWiremock - Starting BugWiremock on BTW72257 with PID 9496 (started by RACHAUMI in C:\Users\RACHAUMI\git\gloud\gloud-app\gloud-aws) 
2017-01-09 15:21:39.384 INFO [main] BugWiremock - No active profile set, falling back to default profiles: default 
2017-01-09 15:21:39.431 INFO [main] GenericWebApplicationContext - Refreshing org.springframework.web.context.support.GenericWebApplicationContext@6ee660fb: startup date [Mon Jan 09 15:21:39 CET 2017]; root of context hierarchy 
2017-01-09 15:21:39.683 INFO [main] AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring 
2017-01-09 15:21:40.058 INFO [main] BugWiremock - Started BugWiremock in 1.159 seconds (JVM running for 3.043) 
2017-01-09 15:21:40.744 DEBUG [main] RequestAddCookies - CookieSpec selected: default 
2017-01-09 15:21:40.760 DEBUG [main] RequestAuthCache - Auth cache not set in the context 
2017-01-09 15:21:40.775 DEBUG [main] wire - http-outgoing-0 >> "GET /my-url/2 HTTP/1.1[\r][\n]" 
2017-01-09 15:21:40.775 DEBUG [main] wire - http-outgoing-0 >> "Host: localhost:56197[\r][\n]" 
2017-01-09 15:21:40.775 DEBUG [main] wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]" 
2017-01-09 15:21:40.775 DEBUG [main] wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_72)[\r][\n]" 
2017-01-09 15:21:40.775 DEBUG [main] wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]" 
2017-01-09 15:21:40.775 DEBUG [main] wire - http-outgoing-0 >> "[\r][\n]" 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-0 << "[read] I/O error: Read timed out" 
2017-01-09 15:21:41.790 DEBUG [main] RequestAddCookies - CookieSpec selected: default 
2017-01-09 15:21:41.790 DEBUG [main] RequestAuthCache - Auth cache not set in the context 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-1 >> "GET /my-url/2 HTTP/1.1[\r][\n]" 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-1 >> "Host: localhost:56197[\r][\n]" 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]" 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-1 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_72)[\r][\n]" 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]" 
2017-01-09 15:21:41.790 DEBUG [main] wire - http-outgoing-1 >> "[\r][\n]" 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-1 << "[read] I/O error: Read timed out" 
2017-01-09 15:21:42.791 DEBUG [main] RequestAddCookies - CookieSpec selected: default 
2017-01-09 15:21:42.791 DEBUG [main] RequestAuthCache - Auth cache not set in the context 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-2 >> "GET /my-url/2 HTTP/1.1[\r][\n]" 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-2 >> "Host: localhost:56197[\r][\n]" 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]" 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-2 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_72)[\r][\n]" 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-2 >> "Accept-Encoding: gzip,deflate[\r][\n]" 
2017-01-09 15:21:42.791 DEBUG [main] wire - http-outgoing-2 >> "[\r][\n]" 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-2 << "[read] I/O error: Read timed out" 
2017-01-09 15:21:43.806 DEBUG [main] RequestAddCookies - CookieSpec selected: default 
2017-01-09 15:21:43.806 DEBUG [main] RequestAuthCache - Auth cache not set in the context 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-3 >> "GET /my-url/2 HTTP/1.1[\r][\n]" 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-3 >> "Host: localhost:56197[\r][\n]" 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-3 >> "Connection: Keep-Alive[\r][\n]" 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-3 >> "User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_72)[\r][\n]" 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-3 >> "Accept-Encoding: gzip,deflate[\r][\n]" 
2017-01-09 15:21:43.806 DEBUG [main] wire - http-outgoing-3 >> "[\r][\n]" 
2017-01-09 15:21:44.821 DEBUG [main] wire - http-outgoing-3 << "[read] I/O error: Read timed out" 
2017-01-09 15:21:49.283 INFO [Thread-1] GenericWebApplicationContext - Closing org.springframework.web.context.support.GenericWebApplicationContext@6ee660fb: startup date [Mon Jan 09 15:21:39 CET 2017]; root of context hierarchy 


The junit error

com.github.tomakehurst.wiremock.client.VerificationException: Expected exactly 4 requests matching the following pattern but received 3:
{
  "url" : "/my-url/2",
  "method" : "GET"
}
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:385)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:368)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:406)
	at com.bouygtel.swad.gloud.aws.s3.service.BugWiremock.get_with_request_timeout(BugWiremock.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule$1.evaluate(WireMockClassRule.java:70)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


Hope It helps you.

**Comment by tomakehurst** [comment]
Thanks, I'll take a look.

I take it you're using the thin WireMock JAR rather than standalone?

**Comment by RaphC** [comment]
my dependency is the standalone one : 

<dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>2.5.0</version>
            <scope>test</scope>
        </dependency>

**Comment by tomakehurst** [comment]
OK, I see what's happening here.

The issue is that previously, only the request was captured in the request journal, so it could happen at the point it was received (or shortly thereafter). From some point in version 2, the response definition and actual response have been included, meaning that the full info is only known when serving has completed.

In this case, since you're putting a fixed delay of 4s before the response is served, that's the minimum possible time before the request log will have caught up.

I'm hesitant about treating this as a bug. I think it's more of a compromise which enabled a set of extra features. In this particular case I think adding the appropriate delay is probably a reasonable thing to do.

**Comment by RaphC** [comment]
Thank you  @tomakehurst for your feedback. So in my test I should wait for the wiremock server process all request before making the verify. Is there any way (other than setting a thread.sleep with an arbitrary delay) to say to wiremock that all request are served before executing my verify ? something like that : 

wireMockStub.complete();
wireMockStub.verify(4, getRequestedFor(urlEqualTo("/my-url/2")));

**Comment by tomakehurst** [comment]
Nothing that neat unfortunately. In your case, since you know exactly how long you're delaying responses by you can just sleep for slightly longer than that. I don't think that's an unreasonable approach to take (although I'd suggest that you can probably get away with much less than 4s when testing timeout behaviour).

Another alternative is to use an async polling approach (for which there are a few libs around to help with) with verify() or findAll().

**Comment by RaphC** [comment]
Ok @tomakehurst. thanks for the information. You made a great job with wiremock !

So I close the issue

**Comment by tomakehurst** [comment]
Thanks!

**Comment by sheetalj2205** [comment]
@tomakehurst I am also having the kind of same issue in my integration test case. I am sharing the error and code snippet here, can you please help me to fix this?

`SignUpEventConsumerTest > testSignUpKafkaEventReceivedAndSuccessfullyHandled() FAILED
    com.github.tomakehurst.wiremock.client.VerificationException: Expected exactly 1 requests matching the following pattern but received 2:
    {
      "urlPattern" : "/users/customer/profiles/844424930132106",
      "method" : "GET"
    }
        at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:538)
        at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:521)
        at com.github.tomakehurst.wiremock.WireMockServer.verify(WireMockServer.java:271)
        at co.tala.atlas.promotions.integration.kafka.consumer.SignUpEventConsumerTest.testSignUpKafkaEventReceivedAndSuccessfullyHandled(SignUpEventConsumerTest.java:32)`
        
        
Code:
`@Test
    public void testSignUpKafkaEventReceivedAndSuccessfullyHandled() {
        SignUpEvent event = createTestSignUpEvent(EnumEventType.SIGN_UP, userId);

        // create stubs
        setSuccessfulServerApiTrackReferralStub(userId, personId);
        setSuccessfulGetExternalIdStub(userId, false);
        setSuccessfulGenerateFirebaseUrlStub();
        setSuccessfulUserProfileResponse(userId);

        // publish test event
        sendEvent(event);

        Awaitility.await().pollDelay(Durations.TWO_SECONDS).until(() -> true);

        wireMockServer.verify(1, getRequestedFor(urlMatching(
                String.format("/users/customer/profiles/%s", userId))));

        wireMockServer.verify(0, postRequestedFor(urlMatching(
                "/api/ReferralRewardTracking/completeAtlasReferral")));

        UserReferralDetailsRow row = userReferralDetailsRepository.getUserReferralDetailsRowByUserId(userId);
        assertNotNull(row);
        assertEquals(row.getReferralUrl(), referralUrl);
        assertEquals(row.getReferralCode(), referralCode);
    }
`

**Comment by tomakehurst** [comment]
Hi @sheetalj2205 to get some help with this I suggest heading over to the Slack community and posting your question in the general or wiremock-open-source channels.
