### ISSUE TITLE
IllegalStateException in MatchesJsonPathPattern.toString()

### ISSUE THREAD

**Issue by andriusvelykis** [tomakehurst/wiremock#580]
Got this in the debugger and was worried my pattern is wrong.. but seems to be a problem with the `MatchesJsonPathPattern` class:

```
java.lang.IllegalStateException: Constructor must have a first parameter annotatated with JsonProperty("<operator name>")
	at com.github.tomakehurst.wiremock.matching.StringValuePattern.getName(StringValuePattern.java:74)
	at com.github.tomakehurst.wiremock.matching.StringValuePattern.toString(StringValuePattern.java:59)
...
```

To reproduce, run the following code:

```java
    StringValuePattern jsonPathPattern = WireMock.matchingJsonPath("$..*");
    jsonPathPattern.toString();
```

**Comment by tomakehurst** [comment]
Thanks, yes that should be annotated.
