### ISSUE TITLE
2.5.1 stubs are unreadable by WireMock 2.1.7 

### ISSUE THREAD

**Issue by marcingrzejszczak** [tomakehurst/wiremock#599]
Obviously it's my bad that I haven't bumped up WireMock but anyways... The problem looks as follows.

At some point WireMock has started adding `id` and `uuid` fields to the JSON. Unfortunately old versions of WireMock are very strict about what should be there in the `StubMapping` so they are not happy to see those fields there. Example:

WireMock 2.1.7

```json
{
  "request" : {
    "method" : "GET"
  },
  "response" : {
    "status" : 200
  }
}
```

WireMock 2.5.1

```json
{
  "id" : "77514bd4-a102-4478-a3c0-0fda8b905591",
  "request" : {
    "method" : "GET"
  },
  "response" : {
    "status" : 200
  },
  "uuid" : "77514bd4-a102-4478-a3c0-0fda8b905591"
}
```

If you have an app using WireMock `2.1.7` and you get the second stub you get:

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "id" (class com.github.tomakehurst.wiremock.stubbing.StubMapping), not marked as ignorable (7 known properties: "response", "requiredScenarioState", "priority", "uuid", "request", "newScenarioState", "scenarioName"])
 at [Source: {
  "id" : "77514bd4-a102-4478-a3c0-0fda8b905591",
  "request" : {
    "method" : "GET"
  },
  "response" : {
    "status" : 200
  },
  "uuid" : "77514bd4-a102-4478-a3c0-0fda8b905591"
}; line: 2, column: 11] (through reference chain: com.github.tomakehurst.wiremock.stubbing.StubMapping["id"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1477)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1455)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
	at com.github.tomakehurst.wiremock.common.Json.read(Json.java:38)
	at com.github.tomakehurst.wiremock.stubbing.StubMapping.buildFrom(StubMapping.java:62)
```

Repo (just build and it will fail) https://github.com/marcingrzejszczak/wiremock_217_vs_251

So I guess the only way on our (library users) side is to try to parse the thing and if it fails due to `UnrecognizedPropertyException` then we should try to do sth about it (for example remove those unrecognized fields). WDYT?

**Comment by tomakehurst** [comment]
Right, so the problem is that you're trying to use stub generated by a newer version of WM with an older one rather than the other way round?

Generally speaking I'm don't think forwards compatibility is a guarantee I'd ever make (backwards compatibility, yes).

This specific problem won't happen in future as an "ignore unrecognised" flag has been added to the Jackson config since 2.1.7. But obviously I can't go back and change 2.1.7 now, so I'm not sure I can offer advice other than "upgrade to 2.5.1".

**Comment by marcingrzejszczak** [comment]
Awesome - that's what I was expecting. I'll program this on my side (in the code that is using 2.1.7) to remove those fields and everything should work fine. Thanks!
