### ISSUE TITLE
PATCH is not stubable

### ISSUE THREAD

**Issue by marcelalburg** [tomakehurst/wiremock#613]
Hi, 

i'm using vert.x 3.3.3 http client, wich one is making a PATCH Request to an API and if i try to stub this, i get an error from WireMock.

```
java.lang.IllegalArgumentException: (PATCH http://127.0.0.1:53232/api/v2/users/123)@84775060 wiremock.org.eclipse.jetty.server.Request@50d9094 does not have a getUri or getHttpURI method
	at com.github.tomakehurst.wiremock.jetty9.JettyUtils.getUri(JettyUtils.java:44) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.isBrowserProxyRequest(WireMockHttpServletRequestAdapter.java:213) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:54) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:75) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:157) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:44) ~[wiremock-standalone-2.5.1.jar:?]
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:100) ~[wiremock-standalone-2.5.1.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) ~[wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) ~[wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) ~[wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [wiremock-standalone-2.5.1.jar:?]
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [wiremock-standalone-2.5.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

i try to stub the request like this, but i guess, the problem is a little bit earlier

```
stubFor(patch(urlMatching("^/api/v2/users/*")).willReturn(aResponse().withStatus(200).withBody(new JsonObject().toString()).withHeader("content-type", "application/json")));`
```

I debug the error and check the values of the wiremock.org.eclipse.jetty.server.Request object and see, that the property "_uri" is a HttpUri with the value "http://127.0.0.1:53262/api/v2/users/123".

Thanks
Marcel

**Comment by tomakehurst** [comment]
I don't think this is specifically a problem with PATCH requests, as you're the second person to report this error in 2.5.1.

I can't replicate the error you're seeing (nor could I replicate the other instance that's been reported), so please could you post your code (or code that reliably produces the problem) and dependencies?

**Comment by marcelalburg** [comment]
You're right. Now, i've a simple testcase and this one works fine. So, give me a little bit more time and i try to make a bigger test.

Thanks for your help

**Comment by marcelalburg** [comment]
Puhhh, i found it. 

The repo is here: https://github.com/marcelalburg/stub_error_wiremock

but it's complex.

The error is easy. I try to call a URL like this

http://example.org/user/123|123

the pipe is the problem. 

I'm not 100% sure but i guess this pipe is valid without encoding.

Thanks
Marcel

**Comment by marcelalburg** [comment]
Any news ?

Thanks
Marcel

**Comment by tomakehurst** [comment]
Not sure what news you're expecting. I thought you'd found the problem?

Unencoded pipes aren't strictly valid in URLs and Java's `URI` class throws an exception if you try to construct one this way, so I'd definitely suggest avoiding this.

**Comment by marcelalburg** [comment]
Hi,

this is the thing. It's valid in java.net.URI and works in production perfectly and without errors or problems. I like to test this code with wiremock and i get this exception.

```
	@Test
	public void test() throws MalformedURLException {
		URL x = new URL("http://www.example.org/test|123");

	}
```

Thanks
Marcel

**Comment by marcelalburg** [comment]
Ok, but i see that
URI.create will not work.

I'll take a look, how i can mock this external api.

Thanks
Marcel
