### ISSUE TITLE
OutOfMemoryError - Heap Space

### ISSUE THREAD

**Issue by OS-JaR** [tomakehurst/wiremock#666]
Hi,
I'm using Wiremock 2.60 and currently run into `java.lang.OutOfMemoryError: Java heap space`.
VM-Options (debugging in IntelliJ) : `-Xmx4096m -ea`
WiremockRule:
`    @Rule
    public WireMockRule wireMockRule = new WireMockRule(WireMockConfiguration.options().port(PORT).disableRequestJournal());`

Request:
`stubFor(post(urlEqualTo("/Endpoint.domain"))
                        .withHeader("Accept", equalTo("text/xml"))
                        .withRequestBody(containing("someString"))
                        .willReturn(aResponse()
                                            .withStatus(200)
                                            .withHeader("Content-Type", "text/xml; charset=utf-8")
                                            .withHeader("Persistent-Auth", "true")
                                            .withBodyFile("/response.xmll")));`

Filesize: Error when files > 200MB
Stacktrace :
`java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringCoding.decode(StringCoding.java:215)
	at java.lang.String.<init>(String.java:463)
	at java.lang.String.<init>(String.java:515)
	at com.github.tomakehurst.wiremock.http.Response.getBodyAsString(Response.java:86)
	at com.github.tomakehurst.wiremock.http.Response.toString(Response.java:120)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:51)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at wiremock.org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at wiremock.org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)`

Any ideas what I'm doing wrong here?

**Comment by tomakehurst** [comment]
Since this is a question and not a bug report or feature request, please can you re-post on the mailing list as per the README.
