### ISSUE TITLE
--help throws the error

### ISSUE THREAD

**Issue by kenorb** [tomakehurst/wiremock#672]
When running standalone version, I see the following error:
```
$ java -jar wiremock-1.58-standalone.jar --help       
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key wiremock.joptsimple.BuiltinHelpFormatter.option.header
	at java.util.ResourceBundle.getObject(ResourceBundle.java:395)
	at java.util.ResourceBundle.getString(ResourceBundle.java:355)
	at wiremock.joptsimple.internal.Messages.message(Messages.java:42)
	at wiremock.joptsimple.BuiltinHelpFormatter.message(BuiltinHelpFormatter.java:553)
	at wiremock.joptsimple.BuiltinHelpFormatter.addHeaders(BuiltinHelpFormatter.java:315)
	at wiremock.joptsimple.BuiltinHelpFormatter.addRows(BuiltinHelpFormatter.java:202)
	at wiremock.joptsimple.BuiltinHelpFormatter.format(BuiltinHelpFormatter.java:98)
	at wiremock.joptsimple.OptionParser.printHelpOn(OptionParser.java:327)
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.captureHelpTextIfRequested(CommandLineOptions.java:120)
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:103)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:49)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:110)
```

It works though when running with `--port 9999`.

**Comment by tomakehurst** [comment]
This is fixed in 2.x
