### ISSUE TITLE
Second https mock server fails

### ISSUE THREAD

**Issue by dr29bart** [tomakehurst/wiremock#677]
Cannot start few https mock servers in the same class:
```Java
import com.github.tomakehurst.wiremock.junit.WireMockRule;
import org.junit.ClassRule;
import org.junit.Test;

public class MockTest {
    @ClassRule
    public static WireMockRule ruleA = new WireMockRule(8080, 8843);
    @ClassRule
    public static WireMockRule ruleB = new WireMockRule(8081, 8844);

    @Test
    public void test() {}
}
```

Fails with

```
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use: bind

	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:145)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:68)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:132)
	at com.github.tomakehurst.wiremock.WireMockServer.start(WireMockServer.java:143)
	... 8 more
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at wiremock.org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at wiremock.org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at wiremock.org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at wiremock.org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at wiremock.org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.start(JettyHttpServer.java:130)
	... 9 more
```

**Comment by tomakehurst** [comment]
Works fine for me. Sure you don't have something else running on port 8080?

**Comment by dr29bart** [comment]
It was! Sorry for bothering...
Please, close the issue.
