### ISSUE TITLE
Inconsistent Wiremock behavior with Async Http Clients and timeouts

### ISSUE THREAD

**Issue by tkruse** [tomakehurst/wiremock#681]
Hi,

I have wiremock tests sporadically failing. This branch "feature/reset-bug" of my sample repo reproduces the issue on Windows7 / Java8 : https://github.com/tkruse/wiremock-jdk8-examples/tree/feature/reset-bug

(Code inside LambdaRequestMatcherTest.java)

I tried reducing the required elements to reproduce, and it seems to reproduce both the Play async Http Client and a tests involving timeouts are required.

The test structure is simple:
1. stub a PUT endpoint with a response withFixedDelay(110)
2. invoke this endpoint with an AsyncHttpClient with a timeout set to 100ms.
3. verify the number of calls received
4. call resetAll()

In the code I commented out a part using a simple synchronized http client, which works fine.

I believe wiremock should not behave differently with the async or sync client. I cannot tell if the bug would rather be in wiremock or in the Play2 async client code. 

I suspect an error showing in the log (In IntelliJ) is somehow related, and could be used to make wiremock more robust against whatever is happening:
```
11:44:58.092 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /__admin/near-misses/request-pattern HTTP/1.1[\r][\n]"
11:44:58.093 [qtp720167805-22 - /foo] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@62873765{IDLE}:WRITING-->IDLE
11:44:58.093 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 47[\r][\n]"
11:44:58.093 [qtp720167805-45] DEBUG org.eclipse.jetty.io.AbstractConnection - FILLING-->FILLING_FILL_INTERESTED HttpConnection@63b62ef8{FILLING_FILL_INTERESTED}
11:44:58.093 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: text/plain; charset=UTF-8[\r][\n]"
11:44:58.093 [qtp720167805-22 - /foo] DEBUG org.eclipse.jetty.server.HttpOutput - 
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.NetworkTrafficSelectChannelEndPoint.flush(NetworkTrafficSelectChannelEndPoint.java:62)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:686)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140)
	at org.eclipse.jetty.server.HttpOutput.close(HttpOutput.java:171)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.writeAndTranslateExceptions(WireMockHandlerDispatchingServlet.java:166)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.applyResponse(WireMockHandlerDispatchingServlet.java:154)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet$ServletHttpResponder.respond(WireMockHandlerDispatchingServlet.java:121)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:63)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 38 common frames omitted
```

**Comment by tkruse** [comment]
Hi, so I learned some more about Wiremock. It seems that using withFixedDelay(...) will cause a wiremock request handler go to sleep, and unti lit wakes up, calls to e.g. verify(1, getRequestedFor(...)) will fail, even though the get request has already been received.

On the other hand, the handler waking up during a later test method can influence further calls to verify(x, getRequestedFor()). And there is no clean way of just killing the sleeping requestHandler or forcing it to return. I thought ```resetAll()``` would to that, but it seems it does not.

It is possible that the syncronous Http call just takes so much time that the test avoids the race condition.
So what is at fault is our usage of withFixedDelay() and verify(), I guess.


Close if you agree.

**Comment by alfanse** [comment]
I'm getting a similar intermittent error using the client: org.asynchttpclient:async-http-client:2.0.24 
where the client timesout.
System.out after each test shows: 
- wiremockrule.listAllStubMappings()  correctly setup
- wiremockrule.findUnmatchedRequests() had none.
Suggesting wiremock received the request, responded but somehow not when the client expected it?

At first I thought it was the timeout tests, so I disabled them all and still tests randomly fail when run as a group. 
Individual tests never fail.

We dropped the project back to wiremock version 1.58 and the error happens very very rarely.
is this a wiremock against async client problem?

Windows & linux & mac; jdk 1.8.65+

**Comment by mustaine** [comment]
The issue is not related with async, I think the issue is related with https://github.com/tomakehurst/wiremock/issues/574
