### ISSUE TITLE
WireMock 2.7.0 requires usage of Jetty on the client side

### ISSUE THREAD

**Issue by marcingrzejszczak** [tomakehurst/wiremock#728]
Hi!

I'm trying to bump SC-Contract to WireMock `2.7.0`. We're excluding Jetty from WireMock from the very beginning so that people can use whatever server Boot provides. Much to my surprise it turned out that after bumping things blow up

```
java.lang.NoClassDefFoundError: org/eclipse/jetty/http/HttpStatus

    at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:382)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:368)
    at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:110)
    at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:265)
    at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:260)
    at org.springframework.cloud.contract.stubrunner.provider.wiremock.WireMockHttpServerStub.registerHealthCheck(WireMockHttpServerStub.java:172)
```

It's kind of a breaking change to require that dependency isn't it? Also `HttpStatus` sounds like a class that you can copy and ditch the Jetty dependency fully.

**Comment by tomakehurst** [comment]
Which version of Jetty are you running with? I did wonder about the wisdom of using this class, but it didn't seem all that likely it'd change frequently.

Agree it'd be better to pull out a copy of it for WireMock to own. I'll do that and push it out in a patch release.

**Comment by tomakehurst** [comment]
Fixed in 4e7d5256437d9e546ca66d136f36813078e2eae3

**Comment by marcingrzejszczak** [comment]
That's the thing - I'm not running against any version of Jetty - it's excluded. I saw the fix - looks perfect :)

**Comment by tomakehurst** [comment]
Doesn't SB pull in its own version of Jetty? I'm at a loss as to how you'd be able to run WM at all with it excluded otherwise.
