### ISSUE TITLE
NoClassDefFoundError when deploying in Docker container

### ISSUE THREAD

**Issue by Afbcary** [tomakehurst/wiremock#737]
I have a Wiremock project using Ivy/Ant for dependencies/builds. When I run it from a launch file in Eclipse it successfully starts up the server and requests succeed. However when I build it as a docker image and run it, it crashes immediately. 

docker build:

    `docker build --force-rm -t <REPO_LOCATION>/assignment_form_api_mock:latest -t <REPO_LOCATION>/assignment_form_api_mock:1.0.6 .`

docker run:

    `docker run -d --name form-api-mock -p 10404:8080 <REPO_LOCATION>/assignment_form_api_mock --verbose --extensions="com.gatesbiz.assignmentdispatch.mock.RequestTemplateTransformerGlobal,com.gatesbiz.assignmentdispatch.mock.AdminAreasRequestTransformer,com.gatesbiz.assignmentdispatch.mock.FormsRequestTransformer,com.gatesbiz.assignmentdispatch.mock.VehicleRequestTransformer"`

While loading extensions docker logs this stack trace:

    

```
2017-08-14 18:05:24.276 Verbose logging enabled
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/type/TypeReference
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.github.tomakehurst.wiremock.extension.ExtensionLoader$3.apply(ExtensionLoader.java:75)
    at com.github.tomakehurst.wiremock.extension.ExtensionLoader$3.apply(ExtensionLoader.java:71)
    at wiremock.com.google.common.collect.Iterators$8.transform(Iterators.java:799)
    at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1163)
    at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
    at com.github.tomakehurst.wiremock.extension.ExtensionLoader.asMap(ExtensionLoader.java:43)
    at com.github.tomakehurst.wiremock.extension.ExtensionLoader.loadExtension(ExtensionLoader.java:32)
    at com.github.tomakehurst.wiremock.extension.ExtensionLoader.load(ExtensionLoader.java:39)
    at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.extensionsOfType(CommandLineOptions.java:277)
    at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:80)
    at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:69)
    at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
    at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:113)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.type.TypeReference
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 17 more
```

I saw that people were having version problems with jackson: https://github.com/tomakehurst/wiremock/issues/282

For that reason I'm using wiremock-standalone. I've also tried implicitly overriding the the jackson versions to ensure the same versions of jackson-annotations, jackson-databind, and jackson-core are used. If I don't add the dependencies implicitly I get the same error but the jars brought in are versions:

```
    jackson-annotations-2.1.2.jar
    jackson-core-2.1.3.jar
    jackson-databind-2.1.3.jar

```
Ivy Dependencies:

   ```
 <dependencies>
	    <dependency org="com.github.tomakehurst" name="wiremock-standalone" rev="2.7.1" conf="compile->default"/>
	    <dependency org="io.rest-assured" name="rest-assured" rev="3.0.3" conf="test->default"/>
	    <dependency org="com.gatesbiz.common" name="logback_core" rev="2.0.13" conf="compile->compile;test->test"/>
	    <dependency org="commons-io" name="commons-io" rev="2.5"/>
	    <dependency org="com.fasterxml.jackson.core" name="jackson-annotations" rev="2.9.0"/>
	    <dependency org="com.fasterxml.jackson.core" name="jackson-databind" rev="2.9.0"/>
    	<dependency org="com.fasterxml.jackson.core" name="jackson-core" rev="2.9.0"/>
    </dependencies>
```

**Comment by tomakehurst** [comment]
As per the readme, please can you post questions on the mailing list.
