### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects

### ISSUE THREAD

**Issue by emilabraham** [tomakehurst/wiremock#827]
Having an issue stubbing a request in spock.
Here's the error I get:
```
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects

	at com.github.tomakehurst.wiremock.matching.RequestPattern.<init>(RequestPattern.java:87)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.<clinit>(RequestPattern.java:122)
	at com.github.tomakehurst.wiremock.matching.RequestPatternBuilder.build(RequestPatternBuilder.java:150)
	at com.github.tomakehurst.wiremock.client.BasicMappingBuilder.build(BasicMappingBuilder.java:152)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:286)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:106)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:110)
	at utils.WireMockServerConf.configureForUpdateIdentity(WireMockServerConf.groovy:58)
	at LayerRestAPISpec.it should be able to update a participant's layer identity(LayerRestAPISpec.groovy:84)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```

I'm guessing it has something to do with the guava dependency, but I'm not entirely sure what. I did find this closed issue: https://github.com/tomakehurst/wiremock/issues/780

Is the google/guava repo a better place to deal with this issue?

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.
