### ISSUE TITLE
Stack trace with no detail is logged when malformed mapping JSON present at startup.

### ISSUE THREAD

**Issue by tomakehurst** [tomakehurst/wiremock#831]
e.g.

```
Exception in thread "main" com.github.tomakehurst.wiremock.common.JsonException
        at com.github.tomakehurst.wiremock.common.JsonException.fromJackson(JsonException.java:32)
        at com.github.tomakehurst.wiremock.common.Json.read(Json.java:52)
        at com.github.tomakehurst.wiremock.stubbing.StubMapping.buildFrom(StubMapping.java:66)
        at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:82)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:154)
        at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:150)
        at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:84)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:70)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:65)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:113)
```

**Comment by dunyakirkali** [comment]
@tomakehurst I have the exact same issue with **wiremock-standalone-2.12.0.jar** using the following mapping:

```
{
  "id" : "8d40d3cf-28b6-4c3a-864a-b05d101d265c",
  "name" : "Tasks",
  "request" : {
    "url" : "/tasks",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "bodyFileName": "body.json"
  },
  "uuid" : "8d40d3cf-28b6-4c3a-864a-b05d101d265c",
  "persistent" : true
}

```

**Comment by illyric** [comment]
I am facing the same issue here. I have the following snippet in mappings:
```
"queryParameters": {
  "latitudes" : {
    "matches" : "^48.133044296$"
  },
    "longitudes" : {
      "matches" : "^11.560554875$"
  }
}
```
changing the name of the key `latitudes` and `longitudes` to a key that ends with a numeric value like `waypoint0` and `waypoint1` throws the exception when starting the client.
