### ISSUE TITLE
[Question] Starting WireMock from another project?

### ISSUE THREAD

**Issue by rs77726** [tomakehurst/wiremock#846]
Pardon me for being a noob here. 

I have a maven project (say "x") which has wiremock dependency and all stub mappings. If I run this project as a standalone, it works fine. I am able to access the url mappings I had set here. Now, what I want is to start the wiremock server from within my functional test project(say "y"). 

For this, I have added "x" as a dependency in "y" and I call the `start()` method within "y" before I start running the test. This starts the wiremock server but when I try to access the url, it gives me this output:

```html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
        <title>Error 500 </title>
    </head>
    <body>
        <h2>HTTP ERROR: 500</h2>
        <p>Problem accessing /publisher/get-info/5. Reason:

            <pre>    javax.servlet.http.HttpServletRequest.isAsyncStarted()Z</pre>
        </p>
        <hr />
        <i>
            <small>Powered by Jetty://</small>
        </i>
    </body>
</html>
```

And in the logs, I see:
```java
WARN [qtp1899404826-93] ServletHandler.doHandle(667) | Error for /publisher/get-info/5
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeader(Ljava/lang/String;)Ljava/lang/String;
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:323)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
WARN [qtp1899404826-93] HttpChannel.handle(384) | /publisher/get-info/5
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:684)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rs77726** [comment]
Can anyone please let me know how to get it working? I want to start and stop the wire mock server from within my functional test project.

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the readme.
