### ISSUE TITLE
Class hierarchy issue with Servlet-API

### ISSUE THREAD

**Issue by personal-ravi-gudla** [tomakehurst/wiremock#882]
Hello All, I am planning to use WireMock in our project. Here is the issue I am facing.
**Issue :**  In pom.xml, I have two dependencies added one for servlet-api and another one for wiremock.
It seems Wiremock 2.14.0 version is depending on Servlet 3.0 which is included in wiremock-standalone. jar itself. But due to other servlet-api dependency we have in our project that is taking priority in class loading and wiremock is faling because my project dependency has servlet-api 2.4. which s older version than what wiremock is expecting. It works if I manully push the wiremock jar to the top in class hierarchy. But it gets overriden when ever I do mvn build. 
Here is the exception I can see in logs:
```
18:39:23.873 [qtp20098454-18 - /test/abc] WARN  w.o.e.jetty.servlet.ServletHandler - Error for /test/abc
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletResponse.getHeader(Ljava/lang/String;)Ljava/lang/String;
	at wiremock.org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:323) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [wiremock-standalone-2.14.0.jar:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_10]
18:39:23.873 [qtp20098454-18 - /test/abc] DEBUG w.o.e.jetty.servlet.ServletHandler - Request(GET /test/abc)@86fa96
18:39:23.876 [qtp20098454-18 - /test/abc] WARN  w.o.eclipse.jetty.server.HttpChannel - /test/abc
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:684) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) ~[wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [wiremock-standalone-2.14.0.jar:na]
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [wiremock-standalone-2.14.0.jar:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_10]
18:39:23.878 [qtp20098454-18 - /test/abc] DEBUG w.o.e.jetty.server.HttpConnection - wiremock.org.eclipse.jetty.server.HttpConnection$SendCallback@98ffc3[PROCESSING][i=ResponseInfo{HTTP/1.1 500 javax.servlet.http.HttpServletRequest.isAsyncStarted()Z,332,false},cb=wiremock.org.eclipse.jetty.server.HttpChannel$CommitCallback@bf7c56] generate: NEED_HEADER (null,[p=0,l=332,c=2048,r=332],true)@START
18:39:23.878 [qtp20098454-18 

```

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README.

Also, there are many, many classpath issues discussed both here and on the mailing list, so please take a quick look through these before posting.

**Comment by personal-ravi-gudla** [comment]
Sorry. I will follow mailing list.
