### ISSUE TITLE
When we add WireMock rule when PowerMock rule already exists

### ISSUE THREAD

**Issue by personal-ravi-gudla** [tomakehurst/wiremock#883]
Hello All, I am planning to use WireMock in our project. Here is the issue I am facing.

**Issue :**  In our existing Junit test cases we are already using PowerMockRule . When I add WireMockRule also, I am getting below exception when I run test.

```
18:28:28.950 [main] DEBUG w.o.e.j.u.c.AbstractLifeCycle - stopping qtp18997436{STARTED,8<=8<=10,i=8,q=0}
18:28:28.952 [main] WARN  w.o.e.j.util.thread.QueuedThreadPool - Couldn't stop Thread[qtp18997436-14,5,]
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2090)
	at wiremock.org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:389)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:531)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.access$700(QueuedThreadPool.java:47)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:722)
18:28:28.952 [main] WARN  w.o.e.j.util.thread.QueuedThreadPool - Couldn't stop Thread[qtp18997436-13,5,]
18:28:28.952 [main] DEBUG w.o.e.j.u.c.AbstractLifeCycle - STOPPED qtp18997436{STOPPED,8<=8<=10,i=0,q=4} 

```
Here are the rules I have used.
```
@Rule
    public PowerMockRule rule = new PowerMockRule();

@Rule
public WireMockRule wireMockRule = new WireMockRule(8089); 
```

**Comment by tomakehurst** [comment]
Again, mailing list please.

**Comment by eabud** [comment]
Hey, I am facing the same problem. Did you find a solution for this exception ?

**Comment by nikhilGitrepo** [comment]
@tomakehurst If you are insisting upon people to use mailing list, then please also make sure to add a link its resolution.
