### ISSUE TITLE
java.io.FileNotFoundException -  (Filename too long)

### ISSUE THREAD

**Issue by gustavonalle** [tomakehurst/wiremock#89]
The mapping configurations consider the body file name as matching the request the originated it. 
In case of a very long GET request, the size of file name explodes the Linux limit and the request body is not saved.
Ideally it should store the files names as hashes of the request

**Comment by tomakehurst** [comment]
New recorder coming in #674

**Comment by mleczakm** [comment]
I'm still having same issue on 3.9.2:
```
wiremock-1  | 2024-10-24 11:26:03.002 Admin request received:
wiremock-1  | 100.64.4.1 - POST /recordings/stop
wiremock-1  | 
wiremock-1  | Host: [wiremock.localhost]
wiremock-1  | User-Agent: [Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0]
wiremock-1  | Content-Length: [0]
wiremock-1  | Accept: [*/*]
wiremock-1  | Accept-Encoding: [gzip, deflate, br, zstd]
wiremock-1  | Accept-Language: [pl,en;q=0.5]
wiremock-1  | Dnt: [1]
wiremock-1  | Origin: [http://wiremock.localhost]
wiremock-1  | Priority: [u=0]
wiremock-1  | Referer: [http://wiremock.localhost/__admin/recorder/]
wiremock-1  | Sec-Fetch-Dest: [empty]
wiremock-1  | Sec-Fetch-Mode: [cors]
wiremock-1  | Sec-Fetch-Site: [same-origin]
wiremock-1  | X-Forwarded-For: [100.64.4.1]
wiremock-1  | X-Forwarded-Host: [wiremock.localhost]
wiremock-1  | X-Forwarded-Port: [80]
wiremock-1  | X-Forwarded-Proto: [http]
wiremock-1  | X-Forwarded-Server: [2f19fee6e0f6]
wiremock-1  | X-Real-Ip: [100.64.4.1]
wiremock-1  | 
wiremock-1  | 
wiremock-1  | 2024-10-24 11:26:03.059 Unrecoverable error handling admin request
wiremock-1  | java.nio.file.FileSystemException: ./mappings/get-methodproduct.searchsimilareislocalecodehu_huownerid5b5d1ownerid5b5d2ownerid5b5d3ownerid5b5d4ownerid5b5d5options5bpart_number5doptions5bpart_number_key5de1rmbbbbmoptions5bname5doptions5bbrand_id5doptions5bcategory_id5dkey37922bbec872a23266e79a3e60322cb7-55195080-49ec-4509-81fb-cdd8c32b46ea.json: File name too long
wiremock-1  |   at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
wiremock-1  |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
wiremock-1  |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
wiremock-1  |   at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
wiremock-1  |   at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
wiremock-1  |   at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
wiremock-1  |   at java.base/java.nio.file.Files.write(Unknown Source)
wiremock-1  |   at com.github.tomakehurst.wiremock.common.AbstractFileSource.writeBinaryFileAndTranslateExceptions(AbstractFileSource.java:177)
wiremock-1  |   at com.github.tomakehurst.wiremock.common.AbstractFileSource.writeBinaryFile(AbstractFileSource.java:110)
wiremock-1  |   at com.github.tomakehurst.wiremock.common.AbstractFileSource.writeTextFile(AbstractFileSource.java:104)
wiremock-1  |   at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.save(JsonFileMappingsSource.java:69)
wiremock-1  |   at com.github.tomakehurst.wiremock.core.WireMockApp.addStubMapping(WireMockApp.java:314)
wiremock-1  |   at com.github.tomakehurst.wiremock.recording.Recorder.takeSnapshot(Recorder.java:121)
wiremock-1  |   at com.github.tomakehurst.wiremock.recording.Recorder.stopRecording(Recorder.java:98)
wiremock-1  |   at com.github.tomakehurst.wiremock.core.WireMockApp.stopRecording(WireMockApp.java:573)
wiremock-1  |   at com.github.tomakehurst.wiremock.admin.StopRecordingTask.execute(StopRecordingTask.java:35)
wiremock-1  |   at com.github.tomakehurst.wiremock.http.AdminRequestHandler.handleRequest(AdminRequestHandler.java:86)
wiremock-1  |   at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:73)
wiremock-1  |   at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:165)
wiremock-1  |   at wiremock.jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:314)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:267)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
wiremock-1  |   at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:563)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
wiremock-1  |   at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
wiremock-1  |   at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
wiremock-1  |   at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
wiremock-1  |   at wiremock.org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
wiremock-1  |   at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
wiremock-1  |   at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by tomakehurst** [comment]
@mleczakm I suggest overriding the filename pattern in order to resolve this issue.

**Comment by mleczakm** [comment]
Hi @tomakehurst, I managed to work around the issue, but I still think this is a bug. What do you think about handling it by catching the exception and retrying the file save using a fallback template without query parameters? Ideally, there could also be a warning to notify the user. At the moment, it's breaking the UI when stopping a recording, without any proper notification, and the recorded requests are being lost.

I could prepare a PR with this approach if you're open to it. Let me know your thoughts!

**Comment by tomakehurst** [comment]
We'd be happy to accept a PR - it would be great to have a better solution for this.

However, I think a better design would be to check the filename length against the platform maximum (or maybe set the a hard limit that aligns with Windows' limit) rather than doing it via exception handling.
