### ISSUE TITLE
EqualToXmlPattern#getExpected need to catch prettyPrint exceptions

### ISSUE THREAD

**Issue by chka73** [tomakehurst/wiremock#915]
Version 2.8.0
Running as a WireMockServer inside JUnit TestRule.

When I encounter a near miss and the Diff.java prints the exception message it fails on the pattern.getExpected() call.
On line 111 in Diff.Java it correctly handles the exception for unknown configuration property "indent-number".
Then on line 114 the pattern.getExpected() invokes EqualToXmlPattern#getExpected which does not catch the thrown unchecked Exception (IllegalArgumentException).
So it should return like Diff#formatIfJsonOrXml instead IMHO.

**Comment by tomakehurst** [comment]
2.8.0 is ancient history. Maybe upgrade to the latest version?

**Comment by chka73** [comment]
Same code is still there on master branch. (https://github.com/tomakehurst/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java)

**Comment by tomakehurst** [comment]
So, is it just the code you object to, or have you found a practical case where this is a problem?

**Comment by tomakehurst** [comment]
I'm quite happy to hear about actual issues, but as you can see there's a large and growing backlog and this is only manageable if I prioritise the problems likely to affect people for real. I'm happy to accept that you may have found a real issue in this case, but there are people who turn up just to do drive-by critiques of code they don't like, which I just don't have the luxury of entertaining.

Please could you share a test case the triggers the problem?

**Comment by chka73** [comment]
Ok, fair enough.
I may have overreacted a bit.

Unfortunately I don't have a shareable test case at hand. We run the tests as part of the MuleSoft platform so I don't know how easily shared that is. I will make an effort in exporting it.

**Comment by tomakehurst** [comment]
Thanks, that would be much appreciated.

**Comment by chka73** [comment]
The stacktrace from the error

` java.lang.IllegalArgumentException: Unknown configuration property indent-number`

	at net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4433)
	at net.sf.saxon.s9api.Processor.setConfigurationProperty(Processor.java:348)
	at net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:305)
	at com.github.tomakehurst.wiremock.common.Xml.prettyPrint(Xml.java:45)
	at com.github.tomakehurst.wiremock.matching.EqualToXmlPattern.getExpected(EqualToXmlPattern.java:88)
	at com.github.tomakehurst.wiremock.verification.Diff.toString(Diff.java:114)
	at com.github.tomakehurst.wiremock.client.VerificationException.<init>(VerificationException.java:64)
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedRequestPattern(VerificationException.java:39)
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:523)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:513)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:492)
	at com.github.tomakehurst.wiremock.WireMockServer.verify(WireMockServer.java:237) `

**Comment by tomakehurst** [comment]
OK, this looks like an XML dependency problem. Your stacktrace contains the (older) Saxon implementation of `TransformerFactory` whereas WireMock requires the `javax.xml.transform` version.

I'll add a workaround that avoids trying to set `indent-number` unless we get the Java impl class back.
