### ISSUE TITLE
Jetty bug throwing 500s when passing in binary file

### ISSUE THREAD

**Issue by jrucker-rf** [tomakehurst/wiremock#918]
This is a followup from a previous issue:  https://github.com/tomakehurst/wiremock/issues/909

From the mail list discussion here: https://groups.google.com/forum/#!topic/wiremock-user/dR7JgvN33Ks

The fix for issue 909 seems to have fixed part of the problem, but a new error is returned when passing in a binary file.

Here are the contents of my mock file:

```
 {
   "request": {
     "urlPathPattern": "/break_wiremock",
     "method": "POST"
   },
   "response": {
     "status": "200",
     "jsonBody": {
       "envelopeId": "passed-in-value-{{request.headers.X-return-value}}"
     },
     "transformers": ["response-template"],
     "headers": {
       "Content-Type": "application/json"
     }
   }
 }
```
Here are the contents of the binary file I used for testing:

```
--MYBOUNDARY
Content-Type: application/json
Content-Disposition: form-data

{"emailBlurb":"Thank you "}
--MYBOUNDARY
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
Content-Disposition: file; filename=A Welcome Letter.docx; documentid=

PKÖnnLóº¡VæÂ	[Content_Types].xml≈ñMO„0ÜÔH¸á»W‘∏∞Z°¶¯8Ó"¡J\]{“¸%{
ÙﬂÔ8i#›¶⁄q©îéﬂ˜}f‹*3π|≥¶xÅò¥w;-«¨'Ω“n^±?∑£ü¨H(ú∆;®ÿ
ªúMVRAjó*∂@

--MYBOUNDARY--
```

And this is the error returned by jetty:

```<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>Error 500 Server Error</title>
    </head>
    <body>
        <h2>HTTP ERROR 500</h2>
        <p>Problem accessing /break_wiremock. Reason:

            <pre>    Server Error</pre>
        </p>
        <h3>Caused by:</h3>
        <pre>java.io.IOException: Missing content-disposition
	at wiremock.org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:555)
	at wiremock.org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:400)
	at wiremock.org.eclipse.jetty.server.Request.getParts(Request.java:2147)
	at wiremock.org.eclipse.jetty.server.Request.getParts(Request.java:2099)
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.safelyGetRequestParts(WireMockHttpServletRequestAdapter.java:280)
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.getParts(WireMockHttpServletRequestAdapter.java:264)
	at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:63)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:74)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:163)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:44)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at wiremock.org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at wiremock.org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:301)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
</pre>
        <hr>
        <i>
            <small>Powered by Jetty://</small>
        </i>
        <hr/>
    </body>
</html>```

**Comment by jrucker-rf** [comment]
I've attached the binary file to the mail list thread above, since I can't seem to attach it here, and the formatting of the quoted contents may not copy well.

**Comment by tomakehurst** [comment]
I think this is going to be harder to fix than the empty body issue. In that instance I was able to just catch the exception and return a non-match, but in this instance the body will need to be matched, so unless it can be parsed correctly by Jetty that can't work.

Will have to think on this some more...

**Comment by galan** [comment]
@tomakehurst Were you able to invest some time into this Bug?

Wiremock 2.18.0 itself uses a deprecated jetty 9.2.24.v20180105, updating this dependencies would help a lot.
Downgrading jetty below 9.4.10 might be an option, but it clashes with our Dropwizard 1.3.5 dependencies.

Another thread found: https://groups.google.com/forum/#!topic/wiremock-user/dYjskyLaLSE

**Comment by tomakehurst** [comment]
Nope, 'fraid not.

I'd love to upgrade to the latest version of Jetty, but please see the numerous discussions on here about the need to preserve JDK7 support for the time being.

**Comment by galan** [comment]
I don't want to hijack this issue, but just for completeness, the 9.2 jetty is [deprecated since january 2018](http://www.eclipse.org/jetty/documentation/9.4.11.v20180605/what-jetty-version.html), so you shouldn't really stick to it. If you want to support JDK7, it might be an option to create a 2.x branch for bugfix support.

**Comment by tomakehurst** [comment]
Just keeping a bugfix branch around would mean the Android folks stop getting new features.

I've been saying for about 2 years that I'd like to start building two JARs - one of JDK7 and one for 8, where the latter can track the latest Jetty release.

But as usual the problem is time, and nobody's stepped up to help with this one.
