### ISSUE TITLE
com.github.tomakehurst.wiremock.client.VerificationException: Expected at least one request matching:

### ISSUE THREAD

**Issue by narendrarajput** [tomakehurst/wiremock#945]
I have tried with simple example but its unable to produce the expected result in verification

```
@Rule
public WireMockRule serviceMock = new WireMockRule(new WireMockConfiguration().notifier(new Slf4jNotifier(true)));

@Test
public void exampleTest() {

	stubFor(get(urlEqualTo("/login")).withBasicAuth("narendra", "rajput")
	.withHeader("Accept", equalTo("application/json"))
	.willReturn(aResponse().withStatus(200).withBody("Login Success"))
	.willReturn(ok()));

	verify(postRequestedFor(urlEqualTo("/login"))
        .withHeader("Content-Type", equalTo("application/json")));

}
```
JUnit test stack trace

```
com.github.tomakehurst.wiremock.client.VerificationException: Expected at least one request matching: {
  "url" : "/login",
  "method" : "POST",
  "headers" : {
    "Content-Type" : {
      "equalTo" : "application/json"
    }
  }
}
Requests received: [ ]
	at com.github.tomakehurst.wiremock.client.WireMock.verificationExceptionForNearMisses(WireMock.java:545)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:532)
	at com.github.tomakehurst.wiremock.client.WireMock.verifyThat(WireMock.java:511)
	at com.github.tomakehurst.wiremock.client.WireMock.verify(WireMock.java:549)
	at com.wiremock.test.MockTestDemo.exampleTest(MockTestDemo.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:73)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```
And in Logging 

```
906 [qtp195615004-18] INFO WireMock - Received request to /mappings with body {
  "id" : "4f876f8c-4b8d-43e7-8ba3-51653ee93c02",
  "request" : {
    "url" : "/login",
    "method" : "GET",
    "headers" : {
      "Accept" : {
        "equalTo" : "application/json"
      }
    },
    "basicAuthCredentials" : {
      "username" : "narendra",
      "password" : "rajput"
    }
  },
  "response" : {
    "status" : 200
  },
  "uuid" : "4f876f8c-4b8d-43e7-8ba3-51653ee93c02"
}
1015 [qtp195615004-19] INFO WireMock - Received request to /requests/count with body {
  "url" : "/login",
  "method" : "POST",
  "headers" : {
    "Content-Type" : {
      "equalTo" : "application/json"
    }
  }
}
1078 [qtp195615004-21] INFO WireMock - Received request to /near-misses/request-pattern with body {
  "url" : "/login",
  "method" : "POST",
  "headers" : {
    "Content-Type" : {
      "equalTo" : "application/json"
    }
  }
}
1156 [qtp195615004-20] INFO WireMock - Received request to /requests/find with body {
  "method" : "ANY"
}
```
**Why it is failing in verification step ?**

**Comment by vamc264** [comment]
Hi Narendrarajput, 
Why did you close this ticket? Could you add your solution for this as I'm facing the same issue please?

Thanks
Vamc

**Comment by narendrarajput** [comment]
@vamc264 , please refer[ this ](https://stackoverflow.com/questions/50539505/com-github-tomakehurst-wiremock-client-verificationexception-expected-at-least)
