### ISSUE TITLE
Jetty 9.4.10 does not have org.eclipse.jetty.server.Request.__MULTIPART_INPUT_STREAM

### ISSUE THREAD

**Issue by alexjson** [tomakehurst/wiremock#952]
Wiremock version 2.18.0

Spring boot version 2.0.2.RELEASE
Jetty 9.4.10.v20180503;

org.eclipse.jetty.server.Request.__MULTIPART_INPUT_STREAM is used in
**WireMockHttpServletRequestAdapter**.java its used

    @Override
    @SuppressWarnings("unchecked")
    public Collection<Part> getParts() {
        if (!isMultipart()) {
            return null;
        }

        if (cachedMultiparts == null) {
            try {
                String contentTypeHeaderValue = from(contentTypeHeader().values()).join(Joiner.on(" "));
                InputStream inputStream = new ByteArrayInputStream(getBody());
                MultiPartInputStreamParser inputStreamParser = new MultiPartInputStreamParser(inputStream, contentTypeHeaderValue, null, null);
                request.setAttribute(org.eclipse.jetty.server.Request.__MULTIPART_INPUT_STREAM, inputStreamParser);
                cachedMultiparts = from(safelyGetRequestParts()).transform(new Function<javax.servlet.http.Part, Part>() {
                    @Override
                    public Part apply(javax.servlet.http.Part input) {
                        return WireMockHttpServletMultipartAdapter.from(input);
                    }
                }).toList();
            } catch (IOException | ServletException exception) {
                return throwUnchecked(exception, Collection.class);
            }
        }

        return (cachedMultiparts.size() > 0) ? cachedMultiparts : null;
    }``

I assume this is causing the following exception I'm getting

> java.lang.IllegalStateException: No multipart config for servlet
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.safelyGetRequestParts(WireMockHttpServletRequestAdapter.java:295) [2 skipped]
	at com.github.tomakehurst.wiremock.servlet.WireMockHttpServletRequestAdapter.getParts(WireMockHttpServletRequestAdapter.java:279)
	at com.github.tomakehurst.wiremock.verification.LoggedRequest.createFrom(LoggedRequest.java:70)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:76)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:164)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:44)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at java.lang.Thread.run(Thread.java:748) [25 skipped]

**Comment by alexjson** [comment]
Will run it with the standalone jar instead as it does not support versions above jetty 9.2 currently
