### ISSUE TITLE
java.lang.IllegalArgumentException is returned when url include {

### ISSUE THREAD

**Issue by cosixjin** [tomakehurst/wiremock#962]
Hi,

When below URL send to Mock server

http://localhost:3000/abcd/base/bwf.dll?{msgType:%22SUMMARY%22,lang:%22en%22,fullTicket:DSsXikur7lFVy53GT%2BnFebZoyBWz2%2B11%2Fv9yGGZe%2BSG6fuRyX7HwSATFif%2Bxp1NomyKzDMmh1ZOYyiRlzAWIBUXHG5Ho657p4pPSdz7pghCtoHLLhlzwm4YWbnliXavc,callback:%22RTQ_CallBack%22,input:%22values?hk;1:quote_summary_mi4/hk;hsi:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc:traded_val/hk;hscei:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc/hk;qmto:sec_vrti.last_v%22}&noCacheIE=1214530184265&callback=jQuery17209600544019359635_1530601011979&_=1530601012813

Following error message always appeared and there isn't request send to Mock server side

java.lang.IllegalArgumentException: Illegal character in query at index 19: /abcd/base/bwf.dll?{msgType:%22SUMMARY%22,lang:%22en%22,fullTicket:DSsXikur7lFVy53GT%2BnFebZoyBWz2%2B11%2Fv9yGGZe%2BSG6fuRyX7HwSATFif%2Bxp1NomyKzDMmh1ZOYyiRlzAWIBUXHG5Ho657p4pPSdz7pghCtoHLLhlzwm4YWbnliXavc,callback:%22RTQ_CallBack%22,input:%22values?hk;1:quote_summary_mi4/hk;hsi:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc:traded_val/hk;hscei:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc/hk;qmto:sec_vrti.last_v%22}&noCacheIE=1214530184265&callback=jQuery17209600544019359635_1530601011979&_=1530601012813
	at java.net.URI.create(URI.java:852)
	at com.github.tomakehurst.wiremock.matching.UrlPathPattern.match(UrlPathPattern.java:32)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:61)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:58)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:165)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$2.apply(InMemoryStubMappings.java:170)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$2.apply(InMemoryStubMappings.java:168)
	at wiremock.com.google.common.collect.Iterators$6.computeNext(Iterators.java:617)
	at wiremock.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at wiremock.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at wiremock.com.google.common.collect.Iterators.getNext(Iterators.java:818)
	at wiremock.com.google.common.collect.Iterators.find(Iterators.java:688)
	at wiremock.com.google.common.collect.Iterables.find(Iterables.java:638)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:63)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:163)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:44)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:116)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at wiremock.org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at wiremock.org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in query at index 19: /abcd/base/bwf.dll?{msgType:%22SUMMARY%22,lang:%22en%22,fullTicket:DSsXikur7lFVy53GT%2BnFebZoyBWz2%2B11%2Fv9yGGZe%2BSG6fuRyX7HwSATFif%2Bxp1NomyKzDMmh1ZOYyiRlzAWIBUXHG5Ho657p4pPSdz7pghCtoHLLhlzwm4YWbnliXavc,callback:%22RTQ_CallBack%22,input:%22values?hk;1:quote_summary_mi4/hk;hsi:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc:traded_val/hk;hscei:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc/hk;qmto:sec_vrti.last_v%22}&noCacheIE=1214530184265&callback=jQuery17209600544019359635_1530601011979&_=1530601012813
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 37 more
Caused by:
java.net.URISyntaxException: Illegal character in query at index 19: /abcd/base/bwf.dll?{msgType:%22SUMMARY%22,lang:%22en%22,fullTicket:DSsXikur7lFVy53GT%2BnFebZoyBWz2%2B11%2Fv9yGGZe%2BSG6fuRyX7HwSATFif%2Bxp1NomyKzDMmh1ZOYyiRlzAWIBUXHG5Ho657p4pPSdz7pghCtoHLLhlzwm4YWbnliXavc,callback:%22RTQ_CallBack%22,input:%22values?hk;1:quote_summary_mi4/hk;hsi:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc:traded_val/hk;hscei:sec_vrti.last_v:sec_vrti.change:sec_vrti.change_perc/hk;qmto:sec_vrti.last_v%22}&noCacheIE=1214530184265&callback=jQuery17209600544019359635_1530601011979&_=1530601012813
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	at com.github.tomakehurst.wiremock.matching.UrlPathPattern.match(UrlPathPattern.java:32)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:61)
	at com.github.tomakehurst.wiremock.matching.RequestPattern$1.match(RequestPattern.java:58)
	at com.github.tomakehurst.wiremock.matching.RequestPattern.match(RequestPattern.java:165)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$2.apply(InMemoryStubMappings.java:170)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings$2.apply(InMemoryStubMappings.java:168)
	at wiremock.com.google.common.collect.Iterators$6.computeNext(Iterators.java:617)
	at wiremock.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at wiremock.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at wiremock.com.google.common.collect.Iterators.getNext(Iterators.java:818)
	at wiremock.com.google.common.collect.Iterators.find(Iterators.java:688)
	at wiremock.com.google.common.collect.Iterables.find(Iterables.java:638)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:63)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:163)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:44)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:116)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at wiremock.org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at wiremock.org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:365)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tomakehurst** [comment]
Please post questions to the mailing list as per the README
