### ISSUE TITLE
[Request] Shade com.google.thirdparty.publicsuffix

### ISSUE THREAD

**Issue by pedrovaldevino** [tomakehurst/wiremock#997]
Hello. I'm running into trouble with wiremock 2.18.0 standalone as follows:

java.lang.NoSuchFieldError: EXACT
	at com.google.common.net.InternetDomainName.findPublicSuffix(InternetDomainName.java:158)
	at com.google.common.net.InternetDomainName.<init>(InternetDomainName.java:143)
	at com.google.common.net.InternetDomainName.from(InternetDomainName.java:196)
	at com.google.common.net.InternetDomainName.isValid(InternetDomainName.java:464)

I noticed com.google.thirdparty.publicsuffix is not shaded, which I believe could solve my problem (without having to reorder dependencies, using the regular jar and add exclusions, etc..). Can you shade com.google.thirdparty.publicsuffix? Thanks.

**Comment by tomakehurst** [comment]
Fixed in 7fd45b0de7d4bda61306b458cc5544865391c427
